# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buildings',
            fields=[
                ('buildingid', models.IntegerField(primary_key=True, db_column='buildingID')),
                ('buildingtoken', models.CharField(max_length=200, serialize=False, primary_key=True, db_column='buildingToken')),
                ('version', models.IntegerField(primary_key=True)),
                ('datasource', models.CharField(max_length=200, primary_key=True)),
                ('buildingname', models.CharField(max_length=200, null=True, db_column='buildingName', blank=True)),
                ('comment', models.CharField(max_length=2000, null=True, blank=True)),
                ('associatedproject', models.CharField(max_length=200, null=True, db_column='associatedProject', blank=True)),
                ('quarter', models.CharField(max_length=200, null=True, blank=True)),
                ('street', models.CharField(max_length=200, null=True, blank=True)),
                ('housenumber', models.CharField(max_length=200, null=True, db_column='houseNumber', blank=True)),
                ('zipcode', models.IntegerField(null=True, db_column='ZIPcode', blank=True)),
                ('city', models.CharField(max_length=200, null=True, blank=True)),
                ('state', models.CharField(max_length=200, null=True, blank=True)),
                ('longitude', models.FloatField(null=True, blank=True)),
                ('latitude', models.FloatField(null=True, blank=True)),
                ('altitude', models.FloatField(null=True, blank=True)),
                ('climate', models.CharField(max_length=200, null=True, blank=True)),
                ('weatherexposure', models.CharField(max_length=200, null=True, db_column='weatherExposure', blank=True)),
                ('yearofcompletion', models.IntegerField(null=True, db_column='yearOfCompletion', blank=True)),
                ('monumentalprotection', models.CharField(max_length=200, null=True, db_column='monumentalProtection', blank=True)),
                ('buildingtype', models.CharField(max_length=200, null=True, db_column='buildingType', blank=True)),
                ('architecture', models.CharField(max_length=200, null=True, blank=True)),
                ('cubatur', models.CharField(max_length=200, null=True, blank=True)),
                ('owner', models.CharField(max_length=200, null=True, blank=True)),
                ('user', models.CharField(max_length=200, null=True, blank=True)),
                ('utilization', models.CharField(max_length=200, null=True, blank=True)),
                ('structuralstate', models.CharField(max_length=200, null=True, db_column='structuralState', blank=True)),
                ('technicalstate', models.CharField(max_length=200, null=True, db_column='technicalState', blank=True)),
                ('developmentpotential', models.CharField(max_length=200, null=True, db_column='developmentPotential', blank=True)),
                ('buildingcategorybwz', models.IntegerField(null=True, db_column='buildingCategoryBWZ', blank=True)),
                ('buildingageclass', models.CharField(max_length=8, null=True, db_column='buildingAgeClass', blank=True)),
                ('usablefloorspacenf', models.FloatField(null=True, db_column='usableFloorSpaceNF', blank=True)),
                ('heatedfloorspacengf', models.FloatField(null=True, db_column='heatedFloorSpaceNGF', blank=True)),
                ('grossfloorareabgf', models.FloatField(null=True, db_column='grossFloorAreaBGF', blank=True)),
                ('buildinggroundarea', models.FloatField(null=True, db_column='buildingGroundArea', blank=True)),
                ('avgbuildingheight', models.FloatField(null=True, db_column='avgBuildingHeight', blank=True)),
                ('numberoffloors', models.IntegerField(null=True, db_column='numberOfFloors', blank=True)),
                ('enclosedvolume', models.FloatField(null=True, db_column='enclosedVolume', blank=True)),
                ('wall1area', models.FloatField(null=True, db_column='wall1Area', blank=True)),
                ('wall1azimuth', models.FloatField(null=True, db_column='wall1Azimuth', blank=True)),
                ('wall2area', models.FloatField(null=True, db_column='wall2Area', blank=True)),
                ('wall2azimuth', models.FloatField(null=True, db_column='wall2Azimuth', blank=True)),
                ('wall3area', models.FloatField(null=True, db_column='wall3Area', blank=True)),
                ('wall3azimuth', models.FloatField(null=True, db_column='wall3Azimuth', blank=True)),
                ('wall4area', models.FloatField(null=True, db_column='wall4Area', blank=True)),
                ('wall4azimuth', models.FloatField(null=True, db_column='wall4Azimuth', blank=True)),
                ('envelopingsurface', models.FloatField(null=True, db_column='envelopingSurface', blank=True)),
                ('windowarea', models.FloatField(null=True, db_column='windowArea', blank=True)),
                ('windowwallratio', models.FloatField(null=True, db_column='windowWallRatio', blank=True)),
                ('avgthicknessouterwall', models.FloatField(null=True, db_column='avgThicknessOuterWall', blank=True)),
                ('avgthicknessinnerwall', models.FloatField(null=True, db_column='avgThicknessInnerWall', blank=True)),
                ('avgthicknessinsulation', models.FloatField(null=True, db_column='avgThicknessInsulation', blank=True)),
                ('materialouterwall', models.CharField(max_length=200, null=True, db_column='materialOuterWall', blank=True)),
                ('materialinnerwall', models.CharField(max_length=200, null=True, db_column='materialInnerWall', blank=True)),
                ('materialinsulation', models.CharField(max_length=200, null=True, db_column='materialInsulation', blank=True)),
                ('materialwindowframe', models.CharField(max_length=200, null=True, db_column='materialWindowFrame', blank=True)),
                ('materialwindowglazing', models.CharField(max_length=200, null=True, db_column='materialWindowGlazing', blank=True)),
                ('basematerial', models.CharField(max_length=200, null=True, db_column='baseMaterial', blank=True)),
                ('avguvalue', models.FloatField(null=True, db_column='avgUvalue', blank=True)),
                ('cellar', models.CharField(max_length=2, null=True, blank=True)),
                ('externalshading', models.CharField(max_length=200, null=True, db_column='externalShading', blank=True)),
                ('heating', models.CharField(max_length=2, null=True, blank=True)),
                ('cooling', models.CharField(max_length=2, null=True, blank=True)),
                ('centralizedcoolingsystem', models.CharField(max_length=2, null=True, db_column='centralizedCoolingSystem', blank=True)),
                ('ahu', models.CharField(max_length=2, null=True, db_column='AHU', blank=True)),
                ('absorptionchiller', models.CharField(max_length=2, null=True, db_column='absorptionChiller', blank=True)),
                ('computercenter', models.CharField(max_length=2, null=True, db_column='computerCenter', blank=True)),
                ('laboratory', models.CharField(max_length=2, null=True, blank=True)),
                ('serverroomwiringcenter', models.CharField(max_length=2, null=True, db_column='serverRoomWiringCenter', blank=True)),
                ('heatenergysource', models.CharField(max_length=200, null=True, db_column='heatEnergySource', blank=True)),
                ('heatingsystem', models.CharField(max_length=2000, null=True, db_column='heatingSystem', blank=True)),
                ('coolingsystem', models.CharField(max_length=2000, null=True, db_column='coolingSystem', blank=True)),
                ('ventilationsystem', models.CharField(max_length=2000, null=True, db_column='ventilationSystem', blank=True)),
                ('lightingsystem', models.CharField(max_length=2000, null=True, db_column='lightingSystem', blank=True)),
                ('reasonsforhighconsumption', models.CharField(max_length=2000, null=True, db_column='reasonsForHighConsumption', blank=True)),
                ('renovationmeasures', models.CharField(max_length=2000, null=True, db_column='renovationMeasures', blank=True)),
                ('districtcoolingpower', models.FloatField(null=True, db_column='districtCoolingPower', blank=True)),
                ('districtcoolingtransferstationname', models.CharField(max_length=200, null=True, db_column='districtCoolingTransferStationName', blank=True)),
                ('districtheatingvariabletemppower', models.FloatField(null=True, db_column='districtHeatingVariableTempPower', blank=True)),
                ('districtheatingconstanttemppower', models.FloatField(null=True, db_column='districtHeatingConstantTempPower', blank=True)),
                ('districtheatingtransferstationname', models.CharField(max_length=200, null=True, db_column='districtHeatingTransferStationName', blank=True)),
                ('transferstationcoordinatex', models.FloatField(null=True, db_column='transferStationCoordinateX', blank=True)),
                ('transferstationcoordinatey', models.FloatField(null=True, db_column='transferStationCoordinateY', blank=True)),
                ('ratiousetransferstation', models.FloatField(null=True, db_column='ratioUseTransferStation', blank=True)),
                ('solarthermalmodularea', models.FloatField(null=True, db_column='solarThermalModulArea', blank=True)),
                ('pvproduction', models.FloatField(null=True, db_column='PVProduction', blank=True)),
                ('pvmoduleareabestsuited', models.FloatField(null=True, db_column='PVModuleAreaBestSuited', blank=True)),
                ('pvmoduleareawellsuited', models.FloatField(null=True, db_column='PVModuleAreaWellSuited', blank=True)),
                ('pvmoduleareasuited', models.FloatField(null=True, db_column='PVModuleAreaSuited', blank=True)),
                ('solarmoduleareashadowed', models.FloatField(null=True, db_column='solarModuleAreaShadowed', blank=True)),
                ('solarmodulearea', models.FloatField(null=True, db_column='solarModuleArea', blank=True)),
                ('roofarea', models.FloatField(null=True, db_column='roofArea', blank=True)),
                ('heatconsumption2011', models.FloatField(null=True, db_column='heatConsumption2011', blank=True)),
                ('heatconsumption2011_1', models.FloatField(null=True, db_column='heatConsumption2011_1', blank=True)),
                ('heatconsumption2011_2', models.FloatField(null=True, db_column='heatConsumption2011_2', blank=True)),
                ('heatconsumption2011_3', models.FloatField(null=True, db_column='heatConsumption2011_3', blank=True)),
                ('heatconsumption2011_4', models.FloatField(null=True, db_column='heatConsumption2011_4', blank=True)),
                ('heatconsumption2011_5', models.FloatField(null=True, db_column='heatConsumption2011_5', blank=True)),
                ('heatconsumption2011_6', models.FloatField(null=True, db_column='heatConsumption2011_6', blank=True)),
                ('heatconsumption2011_7', models.FloatField(null=True, db_column='heatConsumption2011_7', blank=True)),
                ('heatconsumption2011_8', models.FloatField(null=True, db_column='heatConsumption2011_8', blank=True)),
                ('heatconsumption2011_9', models.FloatField(null=True, db_column='heatConsumption2011_9', blank=True)),
                ('heatconsumption2011_10', models.FloatField(null=True, db_column='heatConsumption2011_10', blank=True)),
                ('heatconsumption2011_11', models.FloatField(null=True, db_column='heatConsumption2011_11', blank=True)),
                ('heatconsumption2011_12', models.FloatField(null=True, db_column='heatConsumption2011_12', blank=True)),
                ('heatconsumption2012', models.FloatField(null=True, db_column='heatConsumption2012', blank=True)),
                ('heatconsumption2012_1', models.FloatField(null=True, db_column='heatConsumption2012_1', blank=True)),
                ('heatconsumption2012_2', models.FloatField(null=True, db_column='heatConsumption2012_2', blank=True)),
                ('heatconsumption2012_3', models.FloatField(null=True, db_column='heatConsumption2012_3', blank=True)),
                ('heatconsumption2012_4', models.FloatField(null=True, db_column='heatConsumption2012_4', blank=True)),
                ('heatconsumption2012_5', models.FloatField(null=True, db_column='heatConsumption2012_5', blank=True)),
                ('heatconsumption2012_6', models.FloatField(null=True, db_column='heatConsumption2012_6', blank=True)),
                ('heatconsumption2012_7', models.FloatField(null=True, db_column='heatConsumption2012_7', blank=True)),
                ('heatconsumption2012_8', models.FloatField(null=True, db_column='heatConsumption2012_8', blank=True)),
                ('heatconsumption2012_9', models.FloatField(null=True, db_column='heatConsumption2012_9', blank=True)),
                ('heatconsumption2012_10', models.FloatField(null=True, db_column='heatConsumption2012_10', blank=True)),
                ('heatconsumption2012_11', models.FloatField(null=True, db_column='heatConsumption2012_11', blank=True)),
                ('heatconsumption2012_12', models.FloatField(null=True, db_column='heatConsumption2012_12', blank=True)),
                ('heatconsumption2013', models.FloatField(null=True, db_column='heatConsumption2013', blank=True)),
                ('heatconsumption2013_1', models.FloatField(null=True, db_column='heatConsumption2013_1', blank=True)),
                ('heatconsumption2013_2', models.FloatField(null=True, db_column='heatConsumption2013_2', blank=True)),
                ('heatconsumption2013_3', models.FloatField(null=True, db_column='heatConsumption2013_3', blank=True)),
                ('heatconsumption2013_4', models.FloatField(null=True, db_column='heatConsumption2013_4', blank=True)),
                ('heatconsumption2013_5', models.FloatField(null=True, db_column='heatConsumption2013_5', blank=True)),
                ('heatconsumption2013_6', models.FloatField(null=True, db_column='heatConsumption2013_6', blank=True)),
                ('heatconsumption2013_7', models.FloatField(null=True, db_column='heatConsumption2013_7', blank=True)),
                ('heatconsumption2013_8', models.FloatField(null=True, db_column='heatConsumption2013_8', blank=True)),
                ('heatconsumption2013_9', models.FloatField(null=True, db_column='heatConsumption2013_9', blank=True)),
                ('heatconsumption2013_10', models.FloatField(null=True, db_column='heatConsumption2013_10', blank=True)),
                ('heatconsumption2013_11', models.FloatField(null=True, db_column='heatConsumption2013_11', blank=True)),
                ('heatconsumption2013_12', models.FloatField(null=True, db_column='heatConsumption2013_12', blank=True)),
                ('heatconsumptionhvac2011', models.FloatField(null=True, db_column='heatConsumptionHVAC2011', blank=True)),
                ('heatconsumptionhvac2011_1', models.FloatField(null=True, db_column='heatConsumptionHVAC2011_1', blank=True)),
                ('heatconsumptionhvac2011_2', models.FloatField(null=True, db_column='heatConsumptionHVAC2011_2', blank=True)),
                ('heatconsumptionhvac2011_3', models.FloatField(null=True, db_column='heatConsumptionHVAC2011_3', blank=True)),
                ('heatconsumptionhvac2011_4', models.FloatField(null=True, db_column='heatConsumptionHVAC2011_4', blank=True)),
                ('heatconsumptionhvac2011_5', models.FloatField(null=True, db_column='heatConsumptionHVAC2011_5', blank=True)),
                ('heatconsumptionhvac2011_6', models.FloatField(null=True, db_column='heatConsumptionHVAC2011_6', blank=True)),
                ('heatconsumptionhvac2011_7', models.FloatField(null=True, db_column='heatConsumptionHVAC2011_7', blank=True)),
                ('heatconsumptionhvac2011_8', models.FloatField(null=True, db_column='heatConsumptionHVAC2011_8', blank=True)),
                ('heatconsumptionhvac2011_9', models.FloatField(null=True, db_column='heatConsumptionHVAC2011_9', blank=True)),
                ('heatconsumptionhvac2011_10', models.FloatField(null=True, db_column='heatConsumptionHVAC2011_10', blank=True)),
                ('heatconsumptionhvac2011_11', models.FloatField(null=True, db_column='heatConsumptionHVAC2011_11', blank=True)),
                ('heatconsumptionhvac2011_12', models.FloatField(null=True, db_column='heatConsumptionHVAC2011_12', blank=True)),
                ('heatconsumptionhvac2012', models.FloatField(null=True, db_column='heatConsumptionHVAC2012', blank=True)),
                ('heatconsumptionhvac2012_1', models.FloatField(null=True, db_column='heatConsumptionHVAC2012_1', blank=True)),
                ('heatconsumptionhvac2012_2', models.FloatField(null=True, db_column='heatConsumptionHVAC2012_2', blank=True)),
                ('heatconsumptionhvac2012_3', models.FloatField(null=True, db_column='heatConsumptionHVAC2012_3', blank=True)),
                ('heatconsumptionhvac2012_4', models.FloatField(null=True, db_column='heatConsumptionHVAC2012_4', blank=True)),
                ('heatconsumptionhvac2012_5', models.FloatField(null=True, db_column='heatConsumptionHVAC2012_5', blank=True)),
                ('heatconsumptionhvac2012_6', models.FloatField(null=True, db_column='heatConsumptionHVAC2012_6', blank=True)),
                ('heatconsumptionhvac2012_7', models.FloatField(null=True, db_column='heatConsumptionHVAC2012_7', blank=True)),
                ('heatconsumptionhvac2012_8', models.FloatField(null=True, db_column='heatConsumptionHVAC2012_8', blank=True)),
                ('heatconsumptionhvac2012_9', models.FloatField(null=True, db_column='heatConsumptionHVAC2012_9', blank=True)),
                ('heatconsumptionhvac2012_10', models.FloatField(null=True, db_column='heatConsumptionHVAC2012_10', blank=True)),
                ('heatconsumptionhvac2012_11', models.FloatField(null=True, db_column='heatConsumptionHVAC2012_11', blank=True)),
                ('heatconsumptionhvac2012_12', models.FloatField(null=True, db_column='heatConsumptionHVAC2012_12', blank=True)),
                ('heatconsumptionhvac2013', models.FloatField(null=True, db_column='heatConsumptionHVAC2013', blank=True)),
                ('heatconsumptionhvac2013_1', models.FloatField(null=True, db_column='heatConsumptionHVAC2013_1', blank=True)),
                ('heatconsumptionhvac2013_2', models.FloatField(null=True, db_column='heatConsumptionHVAC2013_2', blank=True)),
                ('heatconsumptionhvac2013_3', models.FloatField(null=True, db_column='heatConsumptionHVAC2013_3', blank=True)),
                ('heatconsumptionhvac2013_4', models.FloatField(null=True, db_column='heatConsumptionHVAC2013_4', blank=True)),
                ('heatconsumptionhvac2013_5', models.FloatField(null=True, db_column='heatConsumptionHVAC2013_5', blank=True)),
                ('heatconsumptionhvac2013_6', models.FloatField(null=True, db_column='heatConsumptionHVAC2013_6', blank=True)),
                ('heatconsumptionhvac2013_7', models.FloatField(null=True, db_column='heatConsumptionHVAC2013_7', blank=True)),
                ('heatconsumptionhvac2013_8', models.FloatField(null=True, db_column='heatConsumptionHVAC2013_8', blank=True)),
                ('heatconsumptionhvac2013_9', models.FloatField(null=True, db_column='heatConsumptionHVAC2013_9', blank=True)),
                ('heatconsumptionhvac2013_10', models.FloatField(null=True, db_column='heatConsumptionHVAC2013_10', blank=True)),
                ('heatconsumptionhvac2013_11', models.FloatField(null=True, db_column='heatConsumptionHVAC2013_11', blank=True)),
                ('heatconsumptionhvac2013_12', models.FloatField(null=True, db_column='heatConsumptionHVAC2013_12', blank=True)),
                ('electricityconsumption2011', models.FloatField(null=True, db_column='electricityConsumption2011', blank=True)),
                ('electricityconsumption2011_1', models.FloatField(null=True, db_column='electricityConsumption2011_1', blank=True)),
                ('electricityconsumption2011_2', models.FloatField(null=True, db_column='electricityConsumption2011_2', blank=True)),
                ('electricityconsumption2011_3', models.FloatField(null=True, db_column='electricityConsumption2011_3', blank=True)),
                ('electricityconsumption2011_4', models.FloatField(null=True, db_column='electricityConsumption2011_4', blank=True)),
                ('electricityconsumption2011_5', models.FloatField(null=True, db_column='electricityConsumption2011_5', blank=True)),
                ('electricityconsumption2011_6', models.FloatField(null=True, db_column='electricityConsumption2011_6', blank=True)),
                ('electricityconsumption2011_7', models.FloatField(null=True, db_column='electricityConsumption2011_7', blank=True)),
                ('electricityconsumption2011_8', models.FloatField(null=True, db_column='electricityConsumption2011_8', blank=True)),
                ('electricityconsumption2011_9', models.FloatField(null=True, db_column='electricityConsumption2011_9', blank=True)),
                ('electricityconsumption2011_10', models.FloatField(null=True, db_column='electricityConsumption2011_10', blank=True)),
                ('electricityconsumption2011_11', models.FloatField(null=True, db_column='electricityConsumption2011_11', blank=True)),
                ('electricityconsumption2011_12', models.FloatField(null=True, db_column='electricityConsumption2011_12', blank=True)),
                ('electricityconsumption2012', models.FloatField(null=True, db_column='electricityConsumption2012', blank=True)),
                ('electricityconsumption2012_1', models.FloatField(null=True, db_column='electricityConsumption2012_1', blank=True)),
                ('electricityconsumption2012_2', models.FloatField(null=True, db_column='electricityConsumption2012_2', blank=True)),
                ('electricityconsumption2012_3', models.FloatField(null=True, db_column='electricityConsumption2012_3', blank=True)),
                ('electricityconsumption2012_4', models.FloatField(null=True, db_column='electricityConsumption2012_4', blank=True)),
                ('electricityconsumption2012_5', models.FloatField(null=True, db_column='electricityConsumption2012_5', blank=True)),
                ('electricityconsumption2012_6', models.FloatField(null=True, db_column='electricityConsumption2012_6', blank=True)),
                ('electricityconsumption2012_7', models.FloatField(null=True, db_column='electricityConsumption2012_7', blank=True)),
                ('electricityconsumption2012_8', models.FloatField(null=True, db_column='electricityConsumption2012_8', blank=True)),
                ('electricityconsumption2012_9', models.FloatField(null=True, db_column='electricityConsumption2012_9', blank=True)),
                ('electricityconsumption2012_10', models.FloatField(null=True, db_column='electricityConsumption2012_10', blank=True)),
                ('electricityconsumption2012_11', models.FloatField(null=True, db_column='electricityConsumption2012_11', blank=True)),
                ('electricityconsumption2012_12', models.FloatField(null=True, db_column='electricityConsumption2012_12', blank=True)),
                ('electricityconsumption2013', models.FloatField(null=True, db_column='electricityConsumption2013', blank=True)),
                ('electricityconsumption2013_1', models.FloatField(null=True, db_column='electricityConsumption2013_1', blank=True)),
                ('electricityconsumption2013_2', models.FloatField(null=True, db_column='electricityConsumption2013_2', blank=True)),
                ('electricityconsumption2013_3', models.FloatField(null=True, db_column='electricityConsumption2013_3', blank=True)),
                ('electricityconsumption2013_4', models.FloatField(null=True, db_column='electricityConsumption2013_4', blank=True)),
                ('electricityconsumption2013_5', models.FloatField(null=True, db_column='electricityConsumption2013_5', blank=True)),
                ('electricityconsumption2013_6', models.FloatField(null=True, db_column='electricityConsumption2013_6', blank=True)),
                ('electricityconsumption2013_7', models.FloatField(null=True, db_column='electricityConsumption2013_7', blank=True)),
                ('electricityconsumption2013_8', models.FloatField(null=True, db_column='electricityConsumption2013_8', blank=True)),
                ('electricityconsumption2013_9', models.FloatField(null=True, db_column='electricityConsumption2013_9', blank=True)),
                ('electricityconsumption2013_10', models.FloatField(null=True, db_column='electricityConsumption2013_10', blank=True)),
                ('electricityconsumption2013_11', models.FloatField(null=True, db_column='electricityConsumption2013_11', blank=True)),
                ('electricityconsumption2013_12', models.FloatField(null=True, db_column='electricityConsumption2013_12', blank=True)),
            ],
            options={
                'db_table': 'buildings',
                'managed': False,
                'verbose_name_plural': 'Buildings',
            },
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('material', models.CharField(max_length=200, serialize=False, primary_key=True)),
                ('category', models.CharField(max_length=200, null=True, blank=True)),
                ('source', models.CharField(max_length=200, null=True, blank=True)),
                ('density', models.FloatField(null=True, blank=True)),
                ('specificheatcapacity', models.FloatField(null=True, db_column='specificHeatCapacity', blank=True)),
                ('heatconductivity', models.FloatField(null=True, db_column='heatConductivity', blank=True)),
                ('diffusionresistancecoefficient', models.FloatField(null=True, db_column='diffusionResistanceCoefficient', blank=True)),
                ('diffusionequivalentairlayerthickness', models.FloatField(null=True, db_column='diffusionEquivalentAirLayerThickness', blank=True)),
                ('sorption', models.FloatField(null=True, blank=True)),
                ('freewatersaturation', models.FloatField(null=True, db_column='freeWaterSaturation', blank=True)),
                ('waterabsorptioncoefficient', models.FloatField(null=True, db_column='waterAbsorptionCoefficient', blank=True)),
                ('openporosity', models.FloatField(null=True, db_column='openPorosity', blank=True)),
                ('shortwavetransmissioncoefficient', models.FloatField(null=True, db_column='shortWaveTransmissionCoefficient', blank=True)),
                ('shortwaveabsorptioncoefficient', models.FloatField(null=True, db_column='shortWaveAbsorptionCoefficient', blank=True)),
                ('shortwavereflectioncoefficient', models.FloatField(null=True, db_column='shortWaveReflectionCoefficient', blank=True)),
                ('longwavetransmissioncoefficient', models.FloatField(null=True, db_column='longWaveTransmissionCoefficient', blank=True)),
                ('longwaveabsorptioncoefficient', models.FloatField(null=True, db_column='longWaveAbsorptionCoefficient', blank=True)),
                ('longwavereflectioncoefficient', models.FloatField(null=True, db_column='longWaveReflectionCoefficient', blank=True)),
            ],
            options={
                'db_table': 'materials',
                'managed': False,
                'verbose_name_plural': 'Materials',
            },
        ),
        migrations.CreateModel(
            name='Quarters',
            fields=[
                ('quarter', models.CharField(max_length=200, serialize=False, primary_key=True)),
                ('associatedproject', models.CharField(max_length=200, null=True, db_column='associatedProject', blank=True)),
                ('longitude', models.FloatField(null=True, blank=True)),
                ('latitude', models.FloatField(null=True, blank=True)),
                ('altitude', models.FloatField(null=True, blank=True)),
                ('climate', models.CharField(max_length=200, null=True, blank=True)),
            ],
            options={
                'db_table': 'quarters',
                'managed': False,
                'verbose_name_plural': 'Quarters',
            },
        ),
        migrations.CreateModel(
            name='SurfacesRaw',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('buildingid', models.IntegerField(null=True, blank=True)),
                ('building2id', models.IntegerField(null=True, blank=True)),
                ('normal_vector_id', models.IntegerField(null=True, blank=True)),
                ('area', models.FloatField(null=True, blank=True)),
                ('azimuth', models.FloatField(null=True, blank=True)),
                ('tilt', models.FloatField(null=True, blank=True)),
                ('vector1_id', models.IntegerField()),
                ('vector2_id', models.IntegerField()),
                ('vector3_id', models.IntegerField()),
                ('vector4_id', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'db_table': 'surfaces_raw',
                'managed': False,
                'verbose_name_plural': 'Surfaces (Raw)',
            },
        ),
        migrations.CreateModel(
            name='Usageprofiles',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('profilename', models.CharField(max_length=200, null=True, db_column='profileName', blank=True)),
                ('hour1', models.FloatField(null=True, blank=True)),
                ('hour2', models.FloatField(null=True, blank=True)),
                ('hour3', models.FloatField(null=True, blank=True)),
                ('hour4', models.FloatField(null=True, blank=True)),
                ('hour5', models.FloatField(null=True, blank=True)),
                ('hour6', models.FloatField(null=True, blank=True)),
                ('hour7', models.FloatField(null=True, blank=True)),
                ('hour8', models.FloatField(null=True, blank=True)),
                ('hour9', models.FloatField(null=True, blank=True)),
                ('hour10', models.FloatField(null=True, blank=True)),
                ('hour11', models.FloatField(null=True, blank=True)),
                ('hour12', models.FloatField(null=True, blank=True)),
                ('hour13', models.FloatField(null=True, blank=True)),
                ('hour14', models.FloatField(null=True, blank=True)),
                ('hour15', models.FloatField(null=True, blank=True)),
                ('hour16', models.FloatField(null=True, blank=True)),
                ('hour17', models.FloatField(null=True, blank=True)),
                ('hour18', models.FloatField(null=True, blank=True)),
                ('hour19', models.FloatField(null=True, blank=True)),
                ('hour20', models.FloatField(null=True, blank=True)),
                ('hour21', models.FloatField(null=True, blank=True)),
                ('hour22', models.FloatField(null=True, blank=True)),
                ('hour23', models.FloatField(null=True, blank=True)),
                ('hour24', models.FloatField(null=True, blank=True)),
            ],
            options={
                'db_table': 'usageProfiles',
                'managed': False,
                'verbose_name_plural': 'Usageprofiles',
            },
        ),
        migrations.CreateModel(
            name='Vectors',
            fields=[
                ('id', models.BigIntegerField(serialize=False, primary_key=True)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
            ],
            options={
                'db_table': 'vectors',
                'managed': False,
                'verbose_name_plural': 'Vectors',
            },
        ),
    ]
