### corellation analysis
build_type_distribution_by_population_density<-function(
  name="distribution_by_population_density",
  description="Buildings with n flats in correlation to population density"){
  l.investigation=new_OeQ_Inv(BLD_DB[,c("POP_DENS",BUILDINGS_BY_NOFLATS)],normcolumn="BLD_NOFLAT_TOTAL",limits=BUILDINGS_BY_NOFLATS_LIMITS)
  l.investigation$distribution_plot(pdffile=name)
  l.investigation$sum_plot(pdffile=paste(name,"_sum",sep=""))
  l.investigation$generate_correlation_function_in_R(fun_name=name,filename=name,description=description,weights=BUILDINGS_BY_NOFLATS_WEIGHTS)
  l.investigation$py_Function(fun_name=name,filename=name,description=description,weights=BUILDINGS_BY_NOFLATS_WEIGHTS)
}

### corellation analysis
build_type_distribution_by_year_of_construction<-function(
  name="distribution_by_year_of_construction",
  description="Buildings with n flats in correlation to year of construction"){
  l.investigation=new_OeQ_Inv(BLD_DB[,c("BLD_AGE1_AVG",BUILDINGS_BY_NOFLATS)],normcolumn="BLD_NOFLAT_TOTAL",p_mode="log")
  l.investigation$distribution_plot(pdffile=name)
  l.investigation$sum_plot(pdffile=paste(name,"_sum",sep=""))
  l.investigation$generate_correlation_function_in_R(fun_name=name,filename=name,description=description,weights=BUILDINGS_BY_NOFLATS_WEIGHTS)
  l.investigation$generate_correlation_function_in_python(fun_name=name,filename=name,description=description,weights=BUILDINGS_BY_NOFLATS_WEIGHTS)
}

### corellation analysis
build_age_distribution_by_average_year_of_construction<-function(
  name="age_distribution_by_average_year_of_construction",
  description="Age distribution in correlation to average year of construction"){
  l.investigation=new_OeQ_Inv(BLD_DB[,c("BLD_AGE1_AVG",BUILDINGS_BY_AGE1)],normcolumn="BLD_AGE1_TOTAL",limits=BUILDINGS_BY_AGE1_LIMITS)
  l.investigation$distribution_plot(pdffile=name)
  l.investigation$sum_plot(pdffile=paste(name,"_sum",sep=""))
  l.investigation$generate_correlation_function_in_R(fun_name=name,filename=name,description=description,weights=BUILDINGS_BY_AGE1_WEIGHTS)
  l.investigation$generate_correlation_function_in_python(fun_name=name,filename=name,description=description,weights=BUILDINGS_BY_AGE1_WEIGHTS)
}

########## Code-/Look-Up-Table Generators  ###########

# Basic Lookup Generator. very straight forward. 
# get the source data
# apply the standard OeQ regression analisys
# use the spline output (smooth if requested)
# generate output lookuptable from prediction
# write the files ####
build_lookup<-function( 
  name="new_lookuptable", #Name of the lookup table, used for all files generated
  description="New autogenerated Lookuptable", #Description for autogenerated functions
  csvsource=NULL, #Source for the lookuptable, KEY is always the first column, VALUE is taken from 'lookup_column'
  lookup_table=NULL, #Only used if there is given no 'csvsource' 
  lookup_column=2, #Column VALUE is taken from
  smoothen=FALSE, #Use smoothed spline prediction for output lookuptable generation
  resolution=20, # resolution of the regression analysis
  prediction_range=NULL, # key range of the prediction, sometimes useful to get smoother behaviour at start and end of the lookuptable
  lookup_range=NULL, # key range of the arising lookuptanble
  write_DB=TRUE, #write the output as RData Database
  dir_DB=getwd(), #directory where the RData Database shall be written to
  write_PDF=TRUE, #write the OeQ regression PDFs
  dir_PDF=getwd(), #directory where the regression PDF shall be written to
  write_CSV=TRUE, #write the output as CSV
  dir_CSV=getwd(),#directory where the CSV lookuptable shall be written to
  write_R=TRUE, #autogenerate a lookupfunction for R
  dir_R=getwd(), #directory where the autogenerated R lookup function shall be written to
  write_py=TRUE, #autogenerate a lookupfunction for Python
  dir_py=getwd(), #directory where the Python lookup function shall be written to
  keyname="KEY", #name of the keycolumn in the lookup table
  valuename="VALUE"){ #name of the valuecolumn in the lookup table
  
  if (!is.null(csvsource)){ #check wether a csv file was given 
    lookup_table=read.csv2(csvsource,skip = 1)[,c(1,lookup_column)] #read it
  }
  if(is.null(lookup_table)){ #stop if there is no lookuptable available
    stop("No Lookup Source !")
  }

  #convert lookup_table to class "lookuptable" if necessary
  if (class(lookup_table)!="lookuptable") lookup_table=lookuptable(lookup_table[,1],lookup_table[,2])
  
  #set prediction_range to the range of 'lookup_table' if not given
  if(is.null(prediction_range)) {
    prediction_range=c(min(keys(lookup_table)),max(keys(lookup_table)))
  }else{
    lookup_table=prepend(lookup_table,prediction_range[1],values(lookup_table)[1])
    lookup_table=append(lookup_table,prediction_range[2],values(lookup_table)[length(values(lookup_table))])
  }
  #set lookup_range to the range of 'lookup_table' if not given
  if(is.null(lookup_range)) lookup_range=prediction_range
  
  #switch warnings off
  suppressWarnings({
  # Apply the standard OeQ regression analysis (normally used to find correlations)
  l.investigation=new_OeQ_Inv(as.data.frame(lookup_table),n_breaks=resolution)
  #switch warnings back to 'warnstatsafe
  })
  
  # Get lookuptable from spline
   if(smoothen) {
    l.lookup_table=lookuptable(c(prediction_range[1]:prediction_range[2]),
                               l.investigation$.regressions$VALUE$.smoothsplinelog$.predict(c(prediction_range[1]:prediction_range[2]),asdf=FALSE)) 
  }else{
    l.lookup_table=lookuptable(c(prediction_range[1]:prediction_range[2]),
                               l.investigation$.regressions$VALUE$.splinelog$.predict(c(prediction_range[1]:prediction_range[2]),asdf=FALSE)) 
  }
 #round values to 2 digits 
  l.lookup_table=round(l.lookup_table,3)
  #set keyrange 
  l.lookup_table=setkeyrange(l.lookup_table,lookup_range[1],lookup_range[2])
  #fix values outside the input data range
  l.lookup_table=limitvalues(l.lookup_table,min(values(lookup_table)),max(values(lookup_table)))
  
  #Plot I/O Comparisonchart
  plot(as.data.frame(l.lookup_table),type="l",col="RED",lwd=3,xlim=lookup_range,xpd=FALSE,
       lab=c(10,10,10),frame.plot=TRUE,tck = 1,fg="GREY80",bty="o",las=1,
       main=paste("I/O Comparison Chart for Look-Up-Table Generation\n'",name,"'",sep=""))
  lines(as.data.frame(lookup_table),xlim=lookup_range,type="b",pch=3,col="GREY30",lty=3,lwd=2,xpd=FALSE)
  box() 
  legend('topright',c("Input Data","Output Look-Up-Table"),col=c('GREY30','RED'), cex=.95,
         lty=c(3,1),lwd=c(2,3),pch=c(3,NA),bty="o",box.lwd=1,bg="white")
  
 
  #write I/O Comparisonchart to pdf
  if(write_PDF) {
   # op <- par()
   pdf(paste(dir_PDF,"/",name,".pdf",sep=""),width=10,height=7,pointsize=17)
    plot(as.data.frame(l.lookup_table),type="l",col="RED",lwd=2,xlim=lookup_range,xpd=FALSE,
         lab=c(10,10,10),frame.plot=TRUE,tck = 1,fg="GREY80",bty="o",las=1,
         main=paste("I/O Comparison Chart for Look-Up-Table Generation\n'",name,"'",sep=""))
    lines(as.data.frame(lookup_table),xlim=lookup_range,type="b",pch=3,col="GREY30",lty=3,lwd=1,xpd=FALSE)
    box() 
    legend('topright',c("Input Data","Output Look-Up-Table"),col=c('GREY30','RED'), cex=.95,
           lty=c(3,1),lwd=c(1,2),pch=c(3,NA),bty="o",box.lwd=1,bg="white")
    dev.off()
  #  suppressWarnings(par(op))
  }
  print(paste(dir_DB,"/",name,".RData",sep=""))
  
  #write RData database
  if(write_DB) save(l.lookup_table,file=paste(dir_DB,"/",name,".RData",sep=""))
  
  #write CSV database
  if(write_CSV){
    write.csv2(as.data.frame(l.lookup_table),file=paste(dir_CSV,"/",name,".csv",sep=""),row.names = FALSE)
  }
  
  #write R lookup function
  if(write_R){
    l.func_text=l.investigation$generate_lookup_function_in_R(fun_name=name,filename=paste(dir_R,"/",name,".R",sep=""),description=description,lookuptable=as.matrix(l.lookup_table))
  }else{
    l.func_text=l.investigation$generate_lookup_function_in_R(fun_name=name,description=description,lookuptable=as.matrix(l.lookup_table))
  }

  #translate R lookup function 
  str_eval(l.func_text)

  #write Python lookup function
  if(write_py){
    l.investigation$generate_lookup_function_in_python(fun_name=name,filename=paste(dir_py,"/",name,".py",sep=""),description=description,lookuptable=l.lookup_table)
  }
  invisible(l.lookup_table)
}




build_typical_window_uvalue_by_year_of_construction_old<-function(
  name="window_uvalue_by_year_of_construction",
  description="Typical Window U-Value in correlation to year of construction"){
  # WINDOW_UVALUE=data.frame(YEAR=c(1800,1920,1950,1977,1995,2010,2050,2100),UVAL_WIN=c(5,4.8,4,3,2,1.3,0.7,0.5)/5,stringsAsFactors=FALSE)
  WINDOW_UVALUE=data.frame(YEAR=c(1800:1950,1977,1980,1995,2010,2050:2100),UVAL_WIN=c(rep(5,151),4,2.5,2,1.5,rep(0.5,51)),stringsAsFactors=FALSE)
  l.investigation=new_OeQ_Inv(WINDOW_UVALUE,n_breaks=10,p_mode="lin")
  #return(l.investigation$.regressions)
  TYP_UVAL_DB_WINDOW=data.frame(YEAR=c(1800:2500),UVAL_WIN=l.investigation$.regressions$UVAL_WIN$.smoothsplinelog$.predict(c(1800:2500))$y,stringsAsFactors = TRUE) 
  TYP_UVAL_DB_WINDOW[,2]=round(TYP_UVAL_DB_WINDOW[,2],2)
  TYP_UVAL_DB_WINDOW=TYP_UVAL_DB_WINDOW[TYP_UVAL_DB_WINDOW[, 1] < 2041, ]
  TYP_UVAL_DB_WINDOW=TYP_UVAL_DB_WINDOW[TYP_UVAL_DB_WINDOW[, 1] > 1849, ]
  TYP_UVAL_DB_WINDOW[TYP_UVAL_DB_WINDOW[,2]>5,2]=5.0
  if(!file.exists("database/oeq_typical_uvalues_window_by_yoc.RData")) save(TYP_UVAL_DB_WINDOW,file="database/oeq_typical_uvalues_window_by_yoc.RData")
  plot(TYP_UVAL_DB_WINDOW)
  WINDOW_UVALUE=cbind(WINDOW_UVALUE,l.investigation$.regressions$UVAL_WIN$.smoothsplinelog$.predict(WINDOW_UVALUE$YEAR)$y)
  l.investigation=new_OeQ_Inv(WINDOW_UVALUE,n_breaks=400,p_mode="lin")
  l.investigation$distribution_plot(pdffile=name)
  # l.investigation$sum_plot(pdffile=paste(name,"_sum",sep=""))
  l.investigation$R_Function_correlation(fun_name=name,filename=name,description=description,lookuptable=TYP_UVAL_DB_WINDOW)
  l.investigation$py_Function(fun_name=name,filename=name,description=description,lookuptable=TYP_UVAL_DB_WINDOW)
  return(TYP_UVAL_DB_WINDOW)
}


build_typical_wall_uvalue_by_year_of_construction<-function(
  name="typical_wall_uvalue_by_year_of_construction",
  description="Typical Wall U-Value in correlation to year of construction, based on the source data of the survey for the \"German Building Typology\ developed by the \"Institut für Wohnen und Umwelt\", Darmstadt/Germany, 2011-2013"){
 # UVALUE=lookuptable(c(1800:1900,1940,1953,1963,1973,1980,1989,2000,2020:2100),c(rep(2.45,101),1.5,1.5,0.9,0.7,0.7,0.4,0.2,rep(0.15,81)))
  CSV=read.csv2("data_sources/150505-U-Values/150505-U-Values.csv/Wall-UWerte.csv",skip = 1,col.names=c("KEY","MIN","MAX","VALUE"))[,c(1,4)]
  UVALUE=lookuptable(CSV[,1],CSV[,2])
  l.investigation=new_OeQ_Inv(as.data.frame(UVALUE),n_breaks=100)

  TYP_UVAL_DB_WALL=data.frame(YEAR=c(1800:2100),UVAL=l.investigation$.regressions$VALUE$.smoothsplinelog$.predict(c(1800:2100),asdf=FALSE),stringsAsFactors = FALSE) 
  TYP_UVAL_DB_WALL[,2]=round(TYP_UVAL_DB_WALL[,2],2)
  TYP_UVAL_DB_WALL=TYP_UVAL_DB_WALL[TYP_UVAL_DB_WALL[, 1] < 2021, ]
  TYP_UVAL_DB_WALL=TYP_UVAL_DB_WALL[TYP_UVAL_DB_WALL[, 1] > 1849, ]
  TYP_UVAL_DB_WALL[TYP_UVAL_DB_WALL[,2]>max(values(UVALUE)),2]=max(values(UVALUE))
  TYP_UVAL_DB_WALL[TYP_UVAL_DB_WALL[,2]<min(values(UVALUE)),2]=min(values(UVALUE))
  if(!file.exists("database/oeq_typical_wall_uvalues_by_yoc.RData")) save(TYP_UVAL_DB_WALL,file="database/oeq_typical_wall_uvalues_by_yoc.RData")
  plot(UVALUE,type="l")
  lines(TYP_UVAL_DB_WALL,col="RED")
  UVALUE=cbind(as.data.frame(UVALUE),l.investigation$.regressions$VALUE$.smoothsplinelog$.predict(as.numeric(keys(UVALUE)),asdf=FALSE))
  l.investigation=new_OeQ_Inv(as.data.frame(UVALUE),n_breaks=100)
  l.investigation$distribution_plot(pdffile=name)
  # l.investigation$sum_plot(pdffile=paste(name,"_sum",sep=""))
  l.func_text=l.investigation$generate_lookup_function_in_R(fun_name=name,filename=name,description=description,lookuptable=TYP_UVAL_DB_WALL)
  str_eval(l.func_text)
  l.investigation$generate_lookup_function_in_python(fun_name=name,filename=name,description=description,lookuptable=TYP_UVAL_DB_WALL)
  plot(TYP_UVAL_DB_WALL)
  points(UVALUE[,-3])
  return(l.func_text)
}

build_typical_window_uvalue_by_year_of_construction<-function(
  name="typical_window_uvalue_by_year_of_construction",
  description="Typical Window U-Value in correlation to year of construction, based on the source data of the survey for the \"German Building Typology\ developed by the \"Institut für Wohnen und Umwelt\", Darmstadt/Germany, 2011-2013"){
  # UVALUE=lookuptable(c(1800:1900,1940,1953,1963,1973,1980,1989,2000,2020:2100),c(rep(2.45,101),1.5,1.5,0.9,0.7,0.7,0.4,0.2,rep(0.15,81)))
  CSV=read.csv2("data_sources/150505-U-Values/150505-U-Values.csv/Window-UWerte.csv",skip = 1)[,c(1,4)]
  UVALUE=lookuptable(CSV[,1],CSV[,2])
  l.investigation=new_OeQ_Inv(as.data.frame(UVALUE),n_breaks=100)
  
  TYP_UVAL_DB=data.frame(YEAR=c(1800:2100),UVAL=l.investigation$.regressions$VALUE$.smoothsplinelog$.predict(c(1800:2100),asdf=FALSE),stringsAsFactors = FALSE) 
  TYP_UVAL_DB[,2]=round(TYP_UVAL_DB[,2],2)
  TYP_UVAL_DB=TYP_UVAL_DB[TYP_UVAL_DB[, 1] < 2021, ]
  TYP_UVAL_DB=TYP_UVAL_DB[TYP_UVAL_DB[, 1] > 1849, ]
  TYP_UVAL_DB[TYP_UVAL_DB[,2]>max(values(UVALUE)),2]=max(values(UVALUE))
  TYP_UVAL_DB[TYP_UVAL_DB[,2]<min(values(UVALUE)),2]=min(values(UVALUE))
  if(!file.exists("database/oeq_typical_window_uvalues_by_yoc.RData")) save(TYP_UVAL_DB,file="database/oeq_typical_window_uvalues_by_yoc.RData")
  plot(UVALUE,type="l")
  lines(TYP_UVAL_DB,col="RED")
  UVALUE=cbind(as.data.frame(UVALUE),l.investigation$.regressions$VALUE$.smoothsplinelog$.predict(as.numeric(keys(UVALUE)),asdf=FALSE))
  l.investigation=new_OeQ_Inv(as.data.frame(UVALUE),n_breaks=100)
  l.investigation$distribution_plot(pdffile=name)
  # l.investigation$sum_plot(pdffile=paste(name,"_sum",sep=""))
  l.func_text=l.investigation$generate_lookup_function_in_R(fun_name=name,filename=name,description=description,lookuptable=TYP_UVAL_DB)
  str_eval(l.func_text)
  l.investigation$generate_lookup_function_in_python(fun_name=name,filename=name,description=description,lookuptable=TYP_UVAL_DB)
  plot(TYP_UVAL_DB)
  points(UVALUE[,-3])
  return(l.func_text)
}

build_typical_flatroof_uvalue_by_year_of_construction<-function(
  name="typical_flatroof_uvalue_by_year_of_construction",
  description="Typical Flat Roof U-Value in correlation to year of construction, based on the source data of the survey for the \"German Building Typology\ developed by the \"Institut für Wohnen und Umwelt\", Darmstadt/Germany, 2011-2013"){
  # UVALUE=lookuptable(c(1800:1900,1940,1953,1963,1973,1980,1989,2000,2020:2100),c(rep(2.45,101),1.5,1.5,0.9,0.7,0.7,0.4,0.2,rep(0.15,81)))
  CSV=read.csv2("data_sources/150505-U-Values/150505-U-Values.csv/Flatroof-UWerte.csv",skip = 1)[,c(1,4)]
  UVALUE=lookuptable(CSV[,1],CSV[,2])
  l.investigation=new_OeQ_Inv(as.data.frame(UVALUE),n_breaks=100)
  
  TYP_UVAL_DB=data.frame(YEAR=c(1800:2100),UVAL=l.investigation$.regressions$VALUE$.smoothsplinelog$.predict(c(1800:2100),asdf=FALSE),stringsAsFactors = FALSE) 
  TYP_UVAL_DB[,2]=round(TYP_UVAL_DB[,2],2)
  TYP_UVAL_DB=TYP_UVAL_DB[TYP_UVAL_DB[, 1] < 2021, ]
  TYP_UVAL_DB=TYP_UVAL_DB[TYP_UVAL_DB[, 1] > 1849, ]
  TYP_UVAL_DB[TYP_UVAL_DB[,2]>max(values(UVALUE)),2]=max(values(UVALUE))
  TYP_UVAL_DB[TYP_UVAL_DB[,2]<min(values(UVALUE)),2]=min(values(UVALUE))
  if(!file.exists("database/oeq_typical_flatroof_uvalues_by_yoc.RData")) save(TYP_UVAL_DB,file="database/oeq_typical_flatroof_uvalues_by_yoc.RData")
  plot(UVALUE,type="l")
  lines(TYP_UVAL_DB,col="RED")
  UVALUE=cbind(as.data.frame(UVALUE),l.investigation$.regressions$VALUE$.smoothsplinelog$.predict(as.numeric(keys(UVALUE)),asdf=FALSE))
  l.investigation=new_OeQ_Inv(as.data.frame(UVALUE),n_breaks=100)
  l.investigation$distribution_plot(pdffile=name)
  # l.investigation$sum_plot(pdffile=paste(name,"_sum",sep=""))
  l.func_text=l.investigation$generate_lookup_function_in_R(fun_name=name,filename=name,description=description,lookuptable=TYP_UVAL_DB)
  str_eval(l.func_text)
  l.investigation$generate_lookup_function_in_python(fun_name=name,filename=name,description=description,lookuptable=TYP_UVAL_DB)
  plot(TYP_UVAL_DB)
  points(UVALUE[,-3])
  return(l.func_text)
}

build_typical_roof_uvalue_by_year_of_construction<-function(
  name="typical_roof_uvalue_by_year_of_construction",
  description="Typical Roof U-Value in correlation to year of construction, based on the source data of the survey for the \"German Building Typology\ developed by the \"Institut für Wohnen und Umwelt\", Darmstadt/Germany, 2011-2013"){
  # UVALUE=lookuptable(c(1800:1900,1940,1953,1963,1973,1980,1989,2000,2020:2100),c(rep(2.45,101),1.5,1.5,0.9,0.7,0.7,0.4,0.2,rep(0.15,81)))
  CSV=read.csv2("data_sources/150505-U-Values/150505-U-Values.csv/Roof-UWerte.csv",skip = 1)[,c(1,4)]
  UVALUE=lookuptable(CSV[,1],CSV[,2])
  l.investigation=new_OeQ_Inv(as.data.frame(UVALUE),n_breaks=100)
  
  TYP_UVAL_DB=data.frame(YEAR=c(1800:2100),UVAL=l.investigation$.regressions$VALUE$.smoothsplinelog$.predict(c(1800:2100),asdf=FALSE),stringsAsFactors = FALSE) 
  TYP_UVAL_DB[,2]=round(TYP_UVAL_DB[,2],2)
  TYP_UVAL_DB=TYP_UVAL_DB[TYP_UVAL_DB[, 1] < 2021, ]
  TYP_UVAL_DB=TYP_UVAL_DB[TYP_UVAL_DB[, 1] > 1849, ]
  TYP_UVAL_DB[TYP_UVAL_DB[,2]>max(values(UVALUE)),2]=max(values(UVALUE))
  TYP_UVAL_DB[TYP_UVAL_DB[,2]<min(values(UVALUE)),2]=min(values(UVALUE))
  if(!file.exists("database/oeq_typical_roof_uvalues_by_yoc.RData")) save(TYP_UVAL_DB,file="database/oeq_typical_roof_uvalues_by_yoc.RData")
  plot(UVALUE,type="l")
  lines(TYP_UVAL_DB,col="RED")
  UVALUE=cbind(as.data.frame(UVALUE),l.investigation$.regressions$VALUE$.smoothsplinelog$.predict(as.numeric(keys(UVALUE)),asdf=FALSE))
  l.investigation=new_OeQ_Inv(as.data.frame(UVALUE),n_breaks=100)
  l.investigation$distribution_plot(pdffile=name)
  # l.investigation$sum_plot(pdffile=paste(name,"_sum",sep=""))
  l.func_text=l.investigation$generate_lookup_function_in_R(fun_name=name,filename=name,description=description,lookuptable=TYP_UVAL_DB)
  str_eval(l.func_text)
  l.investigation$generate_lookup_function_in_python(fun_name=name,filename=name,description=description,lookuptable=TYP_UVAL_DB)
  plot(TYP_UVAL_DB)
  print(UVALUE)
  points(UVALUE[,-3])
  return(l.func_text)
}

build_typical_base_uvalue_by_year_of_construction<-function(
  name="typical_base_uvalue_by_year_of_construction",
  description="Typical Base U-Value in correlation to year of construction, based on the source data of the survey for the \"German Building Typology\ developed by the \"Institut für Wohnen und Umwelt\", Darmstadt/Germany, 2011-2013"){
  # UVALUE=lookuptable(c(1800:1900,1940,1953,1963,1973,1980,1989,2000,2020:2100),c(rep(2.45,101),1.5,1.5,0.9,0.7,0.7,0.4,0.2,rep(0.15,81)))
  CSV=read.csv2("data_sources/150505-U-Values/150505-U-Values.csv/Ground-UWerte.csv",skip = 1)[,c(1,4)]
  UVALUE=lookuptable(CSV[,1],CSV[,2])
  l.investigation=new_OeQ_Inv(as.data.frame(UVALUE),n_breaks=100)
  
  TYP_UVAL_DB=data.frame(YEAR=c(1800:2100),UVAL=l.investigation$.regressions$VALUE$.smoothsplinelog$.predict(c(1800:2100),asdf=FALSE),stringsAsFactors = FALSE) 
  TYP_UVAL_DB[,2]=round(TYP_UVAL_DB[,2],2)
  TYP_UVAL_DB=TYP_UVAL_DB[TYP_UVAL_DB[, 1] < 2021, ]
  TYP_UVAL_DB=TYP_UVAL_DB[TYP_UVAL_DB[, 1] > 1849, ]
  TYP_UVAL_DB[TYP_UVAL_DB[,2]>max(values(UVALUE)),2]=max(values(UVALUE))
  TYP_UVAL_DB[TYP_UVAL_DB[,2]<min(values(UVALUE)),2]=min(values(UVALUE))
  if(!file.exists("database/oeq_typical_base_uvalues_by_yoc.RData")) save(TYP_UVAL_DB,file="database/oeq_typical_base_uvalues_by_yoc.RData")
  plot(UVALUE,type="l")
  lines(TYP_UVAL_DB,col="RED")
  UVALUE=cbind(as.data.frame(UVALUE),l.investigation$.regressions$VALUE$.smoothsplinelog$.predict(as.numeric(keys(UVALUE)),asdf=FALSE))
  l.investigation=new_OeQ_Inv(as.data.frame(UVALUE),n_breaks=100)
  l.investigation$distribution_plot(pdffile=name)
  # l.investigation$sum_plot(pdffile=paste(name,"_sum",sep=""))
  l.func_text=l.investigation$generate_lookup_function_in_R(fun_name=name,filename=name,description=description,lookuptable=TYP_UVAL_DB)
  str_eval(l.func_text)
  l.investigation$generate_lookup_function_in_python(fun_name=name,filename=name,description=description,lookuptable=TYP_UVAL_DB)
  plot(TYP_UVAL_DB)
  print(UVALUE)
  points(UVALUE[,-3])
  return(l.func_text)
}

############## IWU ###############
              ############## Walls ###############

#Contemporary Standard Wall U-Values
build_standard_wall_uvalue_by_year_of_construction<-function(){
  build_lookup(name="standard_wall_uvalue_by_year_of_construction",
               description="Standard Wall U-Value of Buildings in correlation to year of construction, based on the source data of the survey for the \"German Building Typology\ developed by the \"Institut für Wohnen und Umwelt\", Darmstadt/Germany, 2011-2013",
               csvsource="data_sources/150505-U-Values/150505-U-Values.csv/Wall-UWerte.csv",
               lookup_column=4,
               dir_DB=DB_PATH,
               dir_CSV=CSV_PATH,
               dir_PDF=PDF_PATH,
               dir_R=CORR_R_EXPORT_PATH,
               dir_py=CORR_PY_EXPORT_PATH,
               smoothen=FALSE,
               resolution=17,
               prediction_range=c(1800,2100),
               lookup_range=c(1849,2021))
}  

#Typical Present Wall U-Value of Single Family Homes
build_typical_present_wall_uvalue_SFH_by_year_of_construction<-function(){
    build_lookup(name="typical_present_wall_uvalue_SFH_by_year_of_construction",
                 description="Typical Present Wall U-Value of Single Family Homes in correlation to year of construction, based on the source data of the survey for the \"German Building Typology\ developed by the \"Institut für Wohnen und Umwelt\", Darmstadt/Germany, 2011-2013",
                 csvsource="data_sources/150506-CSV-Export UValues IWU/CSV Wall.csv",
                 lookup_column=2,
                 dir_DB=DB_PATH,
                 dir_CSV=CSV_PATH,
                 dir_PDF=PDF_PATH,
                 dir_R=CORR_R_EXPORT_PATH,
                 dir_py=CORR_PY_EXPORT_PATH,
                 smoothen=FALSE,
                 resolution=56,
                 prediction_range=c(1800,2100),
                 lookup_range=c(1849,2021))
  }  

#Typical Present Wall U-Value of Single Detached Houses
build_typical_present_wall_uvalue_SDH_by_year_of_construction<-function(){
  build_lookup(name="typical_present_wall_uvalue_SDH_by_year_of_construction",
               description="Typical Present Wall U-Value of Single Detached Houses in correlation to year of construction, based on the source data of the survey for the \"German Building Typology\ developed by the \"Institut für Wohnen und Umwelt\", Darmstadt/Germany, 2011-2013",
               csvsource="data_sources/150506-CSV-Export UValues IWU/CSV Wall.csv",
               lookup_column=3,
               dir_DB=DB_PATH,
               dir_CSV=CSV_PATH,
               dir_PDF=PDF_PATH,
               dir_R=CORR_R_EXPORT_PATH,
               dir_py=CORR_PY_EXPORT_PATH,
               smoothen=FALSE,
               resolution=57,
               prediction_range=c(1800,2100),
               lookup_range=c(1849,2021))
}  


#Typical Present Wall U-Value of Multifamily Houses
build_typical_present_wall_uvalue_MFH_by_year_of_construction<-function(){
  build_lookup(name="typical_present_wall_uvalue_MFH_by_year_of_construction",
               description="Typical Present Wall U-Value of Multifamily Houses in correlation to year of construction, based on the source data of the survey for the \"German Building Typology\ developed by the \"Institut für Wohnen und Umwelt\", Darmstadt/Germany, 2011-2013",
               csvsource="data_sources/150506-CSV-Export UValues IWU/CSV Wall.csv",
               lookup_column=4,
               dir_DB=DB_PATH,
               dir_CSV=CSV_PATH,
               dir_PDF=PDF_PATH,
               dir_R=CORR_R_EXPORT_PATH,
               dir_py=CORR_PY_EXPORT_PATH,
               smoothen=FALSE,
               resolution=60,
               prediction_range=c(1800,2100),
               lookup_range=c(1849,2021))
}  

#Typical Present Wall U-Value of Large Multifamily Houses
build_typical_present_wall_uvalue_LMFH_by_year_of_construction<-function(){
  build_lookup(name="typical_present_wall_uvalue_LMFH_by_year_of_construction",
               description="Typical Present Wall U-Value of Large Multifamily Houses in correlation to year of construction, based on the source data of the survey for the \"German Building Typology\ developed by the \"Institut für Wohnen und Umwelt\", Darmstadt/Germany, 2011-2013",
               csvsource="data_sources/150506-CSV-Export UValues IWU/CSV Wall.csv",
               lookup_column=5,
               dir_DB=DB_PATH,
               dir_CSV=CSV_PATH,
               dir_PDF=PDF_PATH,
               dir_R=CORR_R_EXPORT_PATH,
               dir_py=CORR_PY_EXPORT_PATH,
               smoothen=FALSE,
               resolution=55,
               prediction_range=c(1800,2100),
               lookup_range=c(1849,2021))
}  

#Typical Present Average Wall U-Value of all types of Residential Houses
build_typical_present_wall_uvalue_AVG_by_year_of_construction<-function(){
  build_lookup(name="typical_present_wall_uvalue_AVG_by_year_of_construction",
               description="Typical Present Average Wall U-Value of Houses in correlation to year of construction, based on the source data of the survey for the \"German Building Typology\ developed by the \"Institut für Wohnen und Umwelt\", Darmstadt/Germany, 2011-2013",
               csvsource="data_sources/150506-CSV-Export UValues IWU/CSV Wall.csv",
               lookup_column=6,
               dir_DB=DB_PATH,
               dir_CSV=CSV_PATH,
               dir_PDF=PDF_PATH,
               dir_R=CORR_R_EXPORT_PATH,
               dir_py=CORR_PY_EXPORT_PATH,
               smoothen=FALSE,
               resolution=54,
               prediction_range=c(1800,2100),
               lookup_range=c(1849,2021))
}  

############## Roofs ###############

#Contemporary Standard Roof U-Values
build_standard_roof_uvalue_by_year_of_construction<-function(){
  build_lookup(name="standard_roof_uvalue_by_year_of_construction",
               description="Standard Roof U-Value of Buildings in correlation to year of construction, based on the source data of the survey for the \"German Building Typology\ developed by the \"Institut für Wohnen und Umwelt\", Darmstadt/Germany, 2011-2013",
               csvsource="data_sources/150505-U-Values/150505-U-Values.csv/Roof-UWerte.csv",
               lookup_column=4,
               dir_DB=DB_PATH,
               dir_CSV=CSV_PATH,
               dir_PDF=PDF_PATH,
               dir_R=CORR_R_EXPORT_PATH,
               dir_py=CORR_PY_EXPORT_PATH,
               smoothen=FALSE,
               resolution=25,
               prediction_range=c(1800,2100),
               lookup_range=c(1849,2021))
}  

#Typical Present Roof U-Value of Single Family Homes
build_typical_present_roof_uvalue_SFH_by_year_of_construction<-function(){
  build_lookup(name="typical_present_roof_uvalue_SFH_by_year_of_construction",
               description="Typical Present Roof U-Value of Single Family Homes in correlation to year of construction, based on the source data of the survey for the \"German Building Typology\ developed by the \"Institut für Wohnen und Umwelt\", Darmstadt/Germany, 2011-2013",
               csvsource="data_sources/150506-CSV-Export UValues IWU/CSV Roof.csv",
               lookup_column=2,
               dir_DB=DB_PATH,
               dir_CSV=CSV_PATH,
               dir_PDF=PDF_PATH,
               dir_R=CORR_R_EXPORT_PATH,
               dir_py=CORR_PY_EXPORT_PATH,
               smoothen=FALSE,
               resolution=51,
               prediction_range=c(1800,2100),
               lookup_range=c(1849,2021))
}  

#Typical Present Roof U-Value of Single Detached Houses
build_typical_present_roof_uvalue_SDH_by_year_of_construction<-function(){
  build_lookup(name="typical_present_roof_uvalue_SDH_by_year_of_construction",
               description="Typical Present Roof U-Value of Single Detached Houses in correlation to year of construction, based on the source data of the survey for the \"German Building Typology\ developed by the \"Institut für Wohnen und Umwelt\", Darmstadt/Germany, 2011-2013",
               csvsource="data_sources/150506-CSV-Export UValues IWU/CSV Roof.csv",
               lookup_column=3,
               dir_DB=DB_PATH,
               dir_CSV=CSV_PATH,
               dir_PDF=PDF_PATH,
               dir_R=CORR_R_EXPORT_PATH,
               dir_py=CORR_PY_EXPORT_PATH,
               smoothen=FALSE,
               resolution=51,
               prediction_range=c(1800,2100),
               lookup_range=c(1849,2021))
}  


#Typical Present Roof U-Value of Multifamily Houses
build_typical_present_roof_uvalue_MFH_by_year_of_construction<-function(){
  build_lookup(name="typical_present_roof_uvalue_MFH_by_year_of_construction",
               description="Typical Present Roof U-Value of Multifamily Houses in correlation to year of construction, based on the source data of the survey for the \"German Building Typology\ developed by the \"Institut für Wohnen und Umwelt\", Darmstadt/Germany, 2011-2013",
               csvsource="data_sources/150506-CSV-Export UValues IWU/CSV Roof.csv",
               lookup_column=4,
               dir_DB=DB_PATH,
               dir_CSV=CSV_PATH,
               dir_PDF=PDF_PATH,
               dir_R=CORR_R_EXPORT_PATH,
               dir_py=CORR_PY_EXPORT_PATH,
               smoothen=FALSE,
               resolution=51,
               prediction_range=c(1800,2100),
               lookup_range=c(1849,2021))
}  

#Typical Present Roof U-Value of Large Multifamily Houses
build_typical_present_roof_uvalue_LMFH_by_year_of_construction<-function(){
  build_lookup(name="typical_present_roof_uvalue_LMFH_by_year_of_construction",
               description="Typical Present Roof U-Value of Large Multifamily Houses in correlation to year of construction, based on the source data of the survey for the \"German Building Typology\ developed by the \"Institut für Wohnen und Umwelt\", Darmstadt/Germany, 2011-2013",
               csvsource="data_sources/150506-CSV-Export UValues IWU/CSV Roof.csv",
               lookup_column=5,
               dir_DB=DB_PATH,
               dir_CSV=CSV_PATH,
               dir_PDF=PDF_PATH,
               dir_R=CORR_R_EXPORT_PATH,
               dir_py=CORR_PY_EXPORT_PATH,
               smoothen=FALSE,
               resolution=46,
               prediction_range=c(1800,2100),
               lookup_range=c(1849,2021))
}  

#Typical Present Average Roof U-Value of all types of Residential Houses
build_typical_present_roof_uvalue_AVG_by_year_of_construction<-function(){
  build_lookup(name="typical_present_roof_uvalue_AVG_by_year_of_construction",
               description="Typical Present Average Roof U-Value of Houses in correlation to year of construction, based on the source data of the survey for the \"German Building Typology\ developed by the \"Institut für Wohnen und Umwelt\", Darmstadt/Germany, 2011-2013",
               csvsource="data_sources/150506-CSV-Export UValues IWU/CSV Roof.csv",
               lookup_column=6,
               dir_DB=DB_PATH,
               dir_CSV=CSV_PATH,
               dir_PDF=PDF_PATH,
               dir_R=CORR_R_EXPORT_PATH,
               dir_py=CORR_PY_EXPORT_PATH,
               smoothen=FALSE,
               resolution=54,
               prediction_range=c(1800,2100),
               lookup_range=c(1849,2021))
}  

############## Base ###############

#Contemporary Standard Base U-Values
build_standard_base_uvalue_by_year_of_construction<-function(){
  build_lookup(name="standard_base_uvalue_by_year_of_construction",
               description="Standard Base U-Value of Buildings in correlation to year of construction, based on the source data of the survey for the \"German Building Typology\ developed by the \"Institut für Wohnen und Umwelt\", Darmstadt/Germany, 2011-2013",
               csvsource="data_sources/150505-U-Values/150505-U-Values.csv/Base-UWerte.csv",
               lookup_column=4,
               dir_DB=DB_PATH,
               dir_CSV=CSV_PATH,
               dir_PDF=PDF_PATH,
               dir_R=CORR_R_EXPORT_PATH,
               dir_py=CORR_PY_EXPORT_PATH,
               smoothen=FALSE,
               resolution=19,
               prediction_range=c(1800,2100),
               lookup_range=c(1849,2021))
}  

#Typical Present Base U-Value of Single Family Homes
build_typical_present_base_uvalue_SFH_by_year_of_construction<-function(){
  build_lookup(name="typical_present_base_uvalue_SFH_by_year_of_construction",
               description="Typical Present Base U-Value of Single Family Homes in correlation to year of construction, based on the source data of the survey for the \"German Building Typology\ developed by the \"Institut für Wohnen und Umwelt\", Darmstadt/Germany, 2011-2013",
               csvsource="data_sources/150506-CSV-Export UValues IWU/CSV Base.csv",
               lookup_column=2,
               dir_DB=DB_PATH,
               dir_CSV=CSV_PATH,
               dir_PDF=PDF_PATH,
               dir_R=CORR_R_EXPORT_PATH,
               dir_py=CORR_PY_EXPORT_PATH,
               smoothen=FALSE,
               resolution=51,
               prediction_range=c(1800,2100),
               lookup_range=c(1849,2021))
}  

#Typical Present Base U-Value of Single Detached Houses
build_typical_present_base_uvalue_SDH_by_year_of_construction<-function(){
  build_lookup(name="typical_present_base_uvalue_SDH_by_year_of_construction",
               description="Typical Present Base U-Value of Single Detached Houses in correlation to year of construction, based on the source data of the survey for the \"German Building Typology\ developed by the \"Institut für Wohnen und Umwelt\", Darmstadt/Germany, 2011-2013",
               csvsource="data_sources/150506-CSV-Export UValues IWU/CSV Base.csv",
               lookup_column=3,
               dir_DB=DB_PATH,
               dir_CSV=CSV_PATH,
               dir_PDF=PDF_PATH,
               dir_R=CORR_R_EXPORT_PATH,
               dir_py=CORR_PY_EXPORT_PATH,
               smoothen=FALSE,
               resolution=45,
               prediction_range=c(1800,2100),
               lookup_range=c(1849,2021))
}  


#Typical Present Base U-Value of Multifamily Houses
build_typical_present_base_uvalue_MFH_by_year_of_construction<-function(){
  build_lookup(name="typical_present_base_uvalue_MFH_by_year_of_construction",
               description="Typical Present Base U-Value of Multifamily Houses in correlation to year of construction, based on the source data of the survey for the \"German Building Typology\ developed by the \"Institut für Wohnen und Umwelt\", Darmstadt/Germany, 2011-2013",
               csvsource="data_sources/150506-CSV-Export UValues IWU/CSV Base.csv",
               lookup_column=4,
               dir_DB=DB_PATH,
               dir_CSV=CSV_PATH,
               dir_PDF=PDF_PATH,
               dir_R=CORR_R_EXPORT_PATH,
               dir_py=CORR_PY_EXPORT_PATH,
               smoothen=FALSE,
               resolution=50,
               prediction_range=c(1800,2100),
               lookup_range=c(1849,2021))
}  

#Typical Present Base U-Value of Large Multifamily Houses
build_typical_present_base_uvalue_LMFH_by_year_of_construction<-function(){
  build_lookup(name="typical_present_base_uvalue_LMFH_by_year_of_construction",
               description="Typical Present Base U-Value of Large Multifamily Houses in correlation to year of construction, based on the source data of the survey for the \"German Building Typology\ developed by the \"Institut für Wohnen und Umwelt\", Darmstadt/Germany, 2011-2013",
               csvsource="data_sources/150506-CSV-Export UValues IWU/CSV Base.csv",
               lookup_column=5,
               dir_DB=DB_PATH,
               dir_CSV=CSV_PATH,
               dir_PDF=PDF_PATH,
               dir_R=CORR_R_EXPORT_PATH,
               dir_py=CORR_PY_EXPORT_PATH,
               smoothen=FALSE,
               resolution=56,
               prediction_range=c(1800,2100),
               lookup_range=c(1849,2021))
}  

#Typical Present Average Base U-Value of all types of Residential Houses
build_typical_present_base_uvalue_AVG_by_year_of_construction<-function(){
  build_lookup(name="typical_present_base_uvalue_AVG_by_year_of_construction",
               description="Typical Present Average Base U-Value of Houses in correlation to year of construction, based on the source data of the survey for the \"German Building Typology\ developed by the \"Institut für Wohnen und Umwelt\", Darmstadt/Germany, 2011-2013",
               csvsource="data_sources/150506-CSV-Export UValues IWU/CSV Base.csv",
               lookup_column=6,
               dir_DB=DB_PATH,
               dir_CSV=CSV_PATH,
               dir_PDF=PDF_PATH,
               dir_R=CORR_R_EXPORT_PATH,
               dir_py=CORR_PY_EXPORT_PATH,
               smoothen=FALSE,
               resolution=48,
               prediction_range=c(1800,2100),
               lookup_range=c(1849,2021))
}  

############## Windows ###############

#Contemporary Standard Window U-Values
build_standard_window_uvalue_by_year_of_construction<-function(){
  build_lookup(name="standard_window_uvalue_by_year_of_construction",
               description="Standard Window U-Value of Buildings in correlation to year of construction, based on the source data of the survey for the \"German Building Typology\ developed by the \"Institut für Wohnen und Umwelt\", Darmstadt/Germany, 2011-2013",
               csvsource="data_sources/150505-U-Values/150505-U-Values.csv/Window-UWerte.csv",
               lookup_column=4,
               dir_DB=DB_PATH,
               dir_CSV=CSV_PATH,
               dir_PDF=PDF_PATH,
               dir_R=CORR_R_EXPORT_PATH,
               dir_py=CORR_PY_EXPORT_PATH,
               smoothen=FALSE,
               resolution=11,
               prediction_range=c(1800,2100),
               lookup_range=c(1849,2021))
}  

#Typical Present Window U-Value of Single Family Homes
build_typical_present_window_uvalue_SFH_by_year_of_construction<-function(){
  build_lookup(name="typical_present_window_uvalue_SFH_by_year_of_construction",
               description="Typical Present Window U-Value of Single Family Homes in correlation to year of construction, based on the source data of the survey for the \"German Building Typology\ developed by the \"Institut für Wohnen und Umwelt\", Darmstadt/Germany, 2011-2013",
               csvsource="data_sources/150506-CSV-Export UValues IWU/CSV Window.csv",
               lookup_column=2,
               dir_DB=DB_PATH,
               dir_CSV=CSV_PATH,
               dir_PDF=PDF_PATH,
               dir_R=CORR_R_EXPORT_PATH,
               dir_py=CORR_PY_EXPORT_PATH,
               smoothen=FALSE,
               resolution=25,
               prediction_range=c(1800,2100),
               lookup_range=c(1849,2021))
}  

#Typical Present Window U-Value of Single Detached Houses
build_typical_present_window_uvalue_SDH_by_year_of_construction<-function(){
  build_lookup(name="typical_present_window_uvalue_SDH_by_year_of_construction",
               description="Typical Present Window U-Value of Single Detached Houses in correlation to year of construction, based on the source data of the survey for the \"German Building Typology\ developed by the \"Institut für Wohnen und Umwelt\", Darmstadt/Germany, 2011-2013",
               csvsource="data_sources/150506-CSV-Export UValues IWU/CSV Window.csv",
               lookup_column=3,
               dir_DB=DB_PATH,
               dir_CSV=CSV_PATH,
               dir_PDF=PDF_PATH,
               dir_R=CORR_R_EXPORT_PATH,
               dir_py=CORR_PY_EXPORT_PATH,
               smoothen=FALSE,
               resolution=25,
               prediction_range=c(1800,2100),
               lookup_range=c(1849,2021))
}  


#Typical Present Window U-Value of Multifamily Houses
build_typical_present_window_uvalue_MFH_by_year_of_construction<-function(){
  build_lookup(name="typical_present_window_uvalue_MFH_by_year_of_construction",
               description="Typical Present Window U-Value of Multifamily Houses in correlation to year of construction, based on the source data of the survey for the \"German Building Typology\ developed by the \"Institut für Wohnen und Umwelt\", Darmstadt/Germany, 2011-2013",
               csvsource="data_sources/150506-CSV-Export UValues IWU/CSV Window.csv",
               lookup_column=4,
               dir_DB=DB_PATH,
               dir_CSV=CSV_PATH,
               dir_PDF=PDF_PATH,
               dir_R=CORR_R_EXPORT_PATH,
               dir_py=CORR_PY_EXPORT_PATH,
               smoothen=FALSE,
               resolution=23,
               prediction_range=c(1800,2100),
               lookup_range=c(1849,2021))
}  

#Typical Present Window U-Value of Large Multifamily Houses
build_typical_present_window_uvalue_LMFH_by_year_of_construction<-function(){
  build_lookup(name="typical_present_window_uvalue_LMFH_by_year_of_construction",
               description="Typical Present Window U-Value of Large Multifamily Houses in correlation to year of construction, based on the source data of the survey for the \"German Building Typology\ developed by the \"Institut für Wohnen und Umwelt\", Darmstadt/Germany, 2011-2013",
               csvsource="data_sources/150506-CSV-Export UValues IWU/CSV Window.csv",
               lookup_column=5,
               dir_DB=DB_PATH,
               dir_CSV=CSV_PATH,
               dir_PDF=PDF_PATH,
               dir_R=CORR_R_EXPORT_PATH,
               dir_py=CORR_PY_EXPORT_PATH,
               smoothen=FALSE,
               resolution=22,
               prediction_range=c(1800,2100),
               lookup_range=c(1849,2021))
}  

#Typical Present Average Window U-Value of all types of Residential Houses
build_typical_present_window_uvalue_AVG_by_year_of_construction<-function(){
  build_lookup(name="typical_present_window_uvalue_AVG_by_year_of_construction",
               description="Typical Present Average Window U-Value of Houses in correlation to year of construction, based on the source data of the survey for the \"German Building Typology\ developed by the \"Institut für Wohnen und Umwelt\", Darmstadt/Germany, 2011-2013",
               csvsource="data_sources/150506-CSV-Export UValues IWU/CSV Window.csv",
               lookup_column=6,
               dir_DB=DB_PATH,
               dir_CSV=CSV_PATH,
               dir_PDF=PDF_PATH,
               dir_R=CORR_R_EXPORT_PATH,
               dir_py=CORR_PY_EXPORT_PATH,
               smoothen=FALSE,
               resolution=18,
               prediction_range=c(1800,2100),
               lookup_range=c(1849,2021))
}  



build_typical_present_window_uvalue_by_year_of_construction<-function(
  name="typical_present_window_uvalue_by_year_of_construction",
  description="Typical Present Window U-Value in correlation to year of construction, based on the source data of the survey for the \"German Building Typology\ developed by the \"Institut für Wohnen und Umwelt\", Darmstadt/Germany, 2011-2013"){
  # UVALUE=lookuptable(c(1800:1900,1940,1953,1963,1973,1980,1989,2000,2020:2100),c(rep(2.45,101),1.5,1.5,0.9,0.7,0.7,0.4,0.2,rep(0.15,81)))
  CSV=read.csv2("data_sources/150506-CSV-Export UValues IWU/CSV Window.csv",skip = 1)[,c(1,4)]
  UVALUE=lookuptable(CSV[,1],CSV[,2])
  l.investigation=new_OeQ_Inv(as.data.frame(UVALUE),n_breaks=20)
  
  TYP_UVAL_DB=data.frame(YEAR=c(1800:2100),UVAL=l.investigation$.regressions$VALUE$.smoothsplinelog$.predict(c(1800:2100),asdf=FALSE),stringsAsFactors = FALSE) 
  TYP_UVAL_DB[,2]=round(TYP_UVAL_DB[,2],2)
  TYP_UVAL_DB=TYP_UVAL_DB[TYP_UVAL_DB[, 1] < 2021, ]
  TYP_UVAL_DB=TYP_UVAL_DB[TYP_UVAL_DB[, 1] > 1849, ]
  TYP_UVAL_DB[TYP_UVAL_DB[,2]>max(values(UVALUE)),2]=max(values(UVALUE))
  TYP_UVAL_DB[TYP_UVAL_DB[,2]<min(values(UVALUE)),2]=min(values(UVALUE))
  if(!file.exists("database/oeq_typical_present_window_uvalues_by_yoc.RData")) save(TYP_UVAL_DB,file="database/oeq_typical_present_window_uvalues_by_yoc.RData")
  plot(UVALUE,type="l")
  lines(TYP_UVAL_DB,col="RED")
  UVALUE=cbind(as.data.frame(UVALUE),l.investigation$.regressions$VALUE$.smoothsplinelog$.predict(as.numeric(keys(UVALUE)),asdf=FALSE))
  l.investigation=new_OeQ_Inv(as.data.frame(UVALUE),n_breaks=100)
  l.investigation$distribution_plot(pdffile=name)
  # l.investigation$sum_plot(pdffile=paste(name,"_sum",sep=""))
  l.func_text=l.investigation$generate_lookup_function_in_R(fun_name=name,filename=name,description=description,lookuptable=TYP_UVAL_DB)
  str_eval(l.func_text)
  l.investigation$generate_lookup_function_in_python(fun_name=name,filename=name,description=description,lookuptable=TYP_UVAL_DB)
  plot(TYP_UVAL_DB)
  points(UVALUE[,-3])
  return(l.func_text)
}


build_typical_present_roof_uvalue_by_year_of_construction<-function(){
  build_lookup(name="typical_present_roof_uvalue_by_year_of_construction",
               description="Typical Present Roof U-Value in correlation to year of construction, based on the source data of the survey for the \"German Building Typology\ developed by the \"Institut für Wohnen und Umwelt\", Darmstadt/Germany, 2011-2013",
               csvsource="data_sources/150506-CSV-Export UValues IWU/CSV Roof.csv",
               lookup_column=4,
               dir_DB=DB_PATH,
               dir_CSV=CSV_PATH,
               dir_PDF=PDF_PATH,
               dir_R=CORR_R_EXPORT_PATH,
               dir_py=CORR_PY_EXPORT_PATH,
               smoothen=FALSE,
               resolution=22,
               prediction_range=c(1800,2100),
               lookup_range=c(1849,2021))
}

build_typical_present_base_uvalue_by_year_of_construction<-function(){
  build_lookup(name="typical_present_base_uvalue_by_year_of_construction_NEW",
               description="Typical Present Base U-Value in correlation to year of construction, based on the source data of the survey for the \"German Building Typology\ developed by the \"Institut für Wohnen und Umwelt\", Darmstadt/Germany, 2011-2013",
               csvsource="data_sources/150506-CSV-Export UValues IWU/CSV Ground.csv",
               lookup_column=4,
               dir_DB=DB_PATH,
               dir_CSV=CSV_PATH,
               dir_PDF=PDF_PATH,
               dir_R=CORR_R_EXPORT_PATH,
               dir_py=CORR_PY_EXPORT_PATH,
               smoothen=FALSE,
               resolution=20,
               prediction_range=c(1800,2100),
               lookup_range=c(1849,2021))
}




#build_typical_base_uvalue_by_year_of_construction()
#build_typical_wall_uvalue_by_year_of_construction()
#build_typical_window_uvalue_by_year_of_construction()
#build_typical_roof_uvalue_by_year_of_construction()
#build_typical_flatroof_uvalue_by_year_of_construction()
