# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mainstay_process_dialog.ui'
#
# Created: Tue Nov 18 15:47:03 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainstayProcess_dialog(object):
    def setupUi(self, MainstayProcess_dialog):
        MainstayProcess_dialog.setObjectName(_fromUtf8("MainstayProcess_dialog"))
        MainstayProcess_dialog.setEnabled(True)
        MainstayProcess_dialog.resize(620, 513)
        MainstayProcess_dialog.setMinimumSize(QtCore.QSize(620, 513))
        MainstayProcess_dialog.setMaximumSize(QtCore.QSize(812, 513))
        MainstayProcess_dialog.setSizeGripEnabled(False)
        MainstayProcess_dialog.setModal(False)
        self.buttonBox = QtGui.QDialogButtonBox(MainstayProcess_dialog)
        self.buttonBox.setEnabled(True)
        self.buttonBox.setGeometry(QtCore.QRect(330, 410, 91, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.process_page = QtGui.QStackedWidget(MainstayProcess_dialog)
        self.process_page.setEnabled(False)
        self.process_page.setGeometry(QtCore.QRect(160, 10, 440, 391))
        self.process_page.setAutoFillBackground(False)
        self.process_page.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.process_page.setFrameShape(QtGui.QFrame.Panel)
        self.process_page.setFrameShadow(QtGui.QFrame.Sunken)
        self.process_page.setLineWidth(2)
        self.process_page.setMidLineWidth(1)
        self.process_page.setObjectName(_fromUtf8("process_page"))
        self.project_basics_page = QtGui.QWidget()
        self.project_basics_page.setObjectName(_fromUtf8("project_basics_page"))
        self.ol_plugin_installed_chckBox = QtGui.QCheckBox(self.project_basics_page)
        self.ol_plugin_installed_chckBox.setEnabled(False)
        self.ol_plugin_installed_chckBox.setGeometry(QtCore.QRect(10, 15, 261, 41))
        self.ol_plugin_installed_chckBox.setCheckable(True)
        self.ol_plugin_installed_chckBox.setObjectName(_fromUtf8("ol_plugin_installed_chckBox"))
        self.project_created_chckBox = QtGui.QCheckBox(self.project_basics_page)
        self.project_created_chckBox.setEnabled(False)
        self.project_created_chckBox.setGeometry(QtCore.QRect(10, 55, 261, 41))
        self.project_created_chckBox.setStyleSheet(_fromUtf8(""))
        self.project_created_chckBox.setCheckable(True)
        self.project_created_chckBox.setObjectName(_fromUtf8("project_created_chckBox"))
        self.osm_layer_loaded_chckBox = QtGui.QCheckBox(self.project_basics_page)
        self.osm_layer_loaded_chckBox.setEnabled(False)
        self.osm_layer_loaded_chckBox.setGeometry(QtCore.QRect(10, 95, 261, 41))
        self.osm_layer_loaded_chckBox.setCheckable(True)
        self.osm_layer_loaded_chckBox.setObjectName(_fromUtf8("osm_layer_loaded_chckBox"))
        self.process_page.addWidget(self.project_basics_page)
        self.investigation_area_page = QtGui.QWidget()
        self.investigation_area_page.setObjectName(_fromUtf8("investigation_area_page"))
        self.textBrowser = QtGui.QTextBrowser(self.investigation_area_page)
        self.textBrowser.setGeometry(QtCore.QRect(120, 100, 256, 192))
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.process_page.addWidget(self.investigation_area_page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.process_page.addWidget(self.page_2)
        self.stackedWidgetPage2 = QtGui.QWidget()
        self.stackedWidgetPage2.setObjectName(_fromUtf8("stackedWidgetPage2"))
        self.process_page.addWidget(self.stackedWidgetPage2)
        self.project_basics_btn = QtGui.QToolButton(MainstayProcess_dialog)
        self.project_basics_btn.setEnabled(True)
        self.project_basics_btn.setGeometry(QtCore.QRect(10, 10, 141, 31))
        self.project_basics_btn.setStyleSheet(_fromUtf8(":active, :hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:0.5, stop:0 rgba(175, 175, 175, 255), stop:1 rgba(230, 230, 230, 203));\n"
"}\n"
":checked {\n"
"    background-color: rgb(234,234,234);\n"
"    border: 1px solid rgb(192,192,192);\n"
"}"))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/openmark.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/checkmark.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.project_basics_btn.setIcon(icon)
        self.project_basics_btn.setIconSize(QtCore.QSize(20, 20))
        self.project_basics_btn.setCheckable(True)
        self.project_basics_btn.setChecked(True)
        self.project_basics_btn.setAutoRepeat(False)
        self.project_basics_btn.setAutoExclusive(False)
        self.project_basics_btn.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.project_basics_btn.setAutoRaise(False)
        self.project_basics_btn.setArrowType(QtCore.Qt.NoArrow)
        self.project_basics_btn.setObjectName(_fromUtf8("project_basics_btn"))
        self.investigation_area_btn = QtGui.QToolButton(MainstayProcess_dialog)
        self.investigation_area_btn.setEnabled(True)
        self.investigation_area_btn.setGeometry(QtCore.QRect(10, 40, 141, 31))
        self.investigation_area_btn.setIcon(icon)
        self.investigation_area_btn.setIconSize(QtCore.QSize(20, 20))
        self.investigation_area_btn.setCheckable(True)
        self.investigation_area_btn.setChecked(False)
        self.investigation_area_btn.setAutoRepeat(False)
        self.investigation_area_btn.setAutoExclusive(False)
        self.investigation_area_btn.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.investigation_area_btn.setAutoRaise(False)
        self.investigation_area_btn.setArrowType(QtCore.Qt.NoArrow)
        self.investigation_area_btn.setObjectName(_fromUtf8("investigation_area_btn"))
        self.building_shapes_btn = QtGui.QToolButton(MainstayProcess_dialog)
        self.building_shapes_btn.setEnabled(True)
        self.building_shapes_btn.setGeometry(QtCore.QRect(10, 90, 141, 31))
        self.building_shapes_btn.setStyleSheet(_fromUtf8(""))
        self.building_shapes_btn.setIcon(icon)
        self.building_shapes_btn.setIconSize(QtCore.QSize(20, 20))
        self.building_shapes_btn.setCheckable(True)
        self.building_shapes_btn.setChecked(False)
        self.building_shapes_btn.setAutoRepeat(False)
        self.building_shapes_btn.setAutoExclusive(False)
        self.building_shapes_btn.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.building_shapes_btn.setAutoRaise(False)
        self.building_shapes_btn.setArrowType(QtCore.Qt.NoArrow)
        self.building_shapes_btn.setObjectName(_fromUtf8("building_shapes_btn"))
        self.oeqstepbutton_4 = QtGui.QToolButton(MainstayProcess_dialog)
        self.oeqstepbutton_4.setEnabled(True)
        self.oeqstepbutton_4.setGeometry(QtCore.QRect(10, 120, 141, 31))
        self.oeqstepbutton_4.setIcon(icon)
        self.oeqstepbutton_4.setIconSize(QtCore.QSize(20, 20))
        self.oeqstepbutton_4.setCheckable(True)
        self.oeqstepbutton_4.setChecked(False)
        self.oeqstepbutton_4.setAutoRepeat(False)
        self.oeqstepbutton_4.setAutoExclusive(False)
        self.oeqstepbutton_4.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.oeqstepbutton_4.setAutoRaise(False)
        self.oeqstepbutton_4.setArrowType(QtCore.Qt.NoArrow)
        self.oeqstepbutton_4.setObjectName(_fromUtf8("oeqstepbutton_4"))
        self.oeqstepbutton_5 = QtGui.QToolButton(MainstayProcess_dialog)
        self.oeqstepbutton_5.setEnabled(True)
        self.oeqstepbutton_5.setGeometry(QtCore.QRect(10, 170, 141, 31))
        self.oeqstepbutton_5.setIcon(icon)
        self.oeqstepbutton_5.setIconSize(QtCore.QSize(20, 20))
        self.oeqstepbutton_5.setCheckable(True)
        self.oeqstepbutton_5.setChecked(False)
        self.oeqstepbutton_5.setAutoRepeat(False)
        self.oeqstepbutton_5.setAutoExclusive(False)
        self.oeqstepbutton_5.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.oeqstepbutton_5.setAutoRaise(False)
        self.oeqstepbutton_5.setArrowType(QtCore.Qt.NoArrow)
        self.oeqstepbutton_5.setObjectName(_fromUtf8("oeqstepbutton_5"))
        self.oeqstepbutton_6 = QtGui.QToolButton(MainstayProcess_dialog)
        self.oeqstepbutton_6.setEnabled(True)
        self.oeqstepbutton_6.setGeometry(QtCore.QRect(10, 200, 141, 31))
        self.oeqstepbutton_6.setIcon(icon)
        self.oeqstepbutton_6.setIconSize(QtCore.QSize(20, 20))
        self.oeqstepbutton_6.setCheckable(True)
        self.oeqstepbutton_6.setChecked(False)
        self.oeqstepbutton_6.setAutoRepeat(False)
        self.oeqstepbutton_6.setAutoExclusive(False)
        self.oeqstepbutton_6.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.oeqstepbutton_6.setAutoRaise(False)
        self.oeqstepbutton_6.setArrowType(QtCore.Qt.NoArrow)
        self.oeqstepbutton_6.setObjectName(_fromUtf8("oeqstepbutton_6"))
        self.oeqstepbutton_7 = QtGui.QToolButton(MainstayProcess_dialog)
        self.oeqstepbutton_7.setEnabled(True)
        self.oeqstepbutton_7.setGeometry(QtCore.QRect(10, 230, 141, 31))
        self.oeqstepbutton_7.setIcon(icon)
        self.oeqstepbutton_7.setIconSize(QtCore.QSize(20, 20))
        self.oeqstepbutton_7.setCheckable(True)
        self.oeqstepbutton_7.setChecked(False)
        self.oeqstepbutton_7.setAutoRepeat(False)
        self.oeqstepbutton_7.setAutoExclusive(False)
        self.oeqstepbutton_7.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.oeqstepbutton_7.setAutoRaise(False)
        self.oeqstepbutton_7.setArrowType(QtCore.Qt.NoArrow)
        self.oeqstepbutton_7.setObjectName(_fromUtf8("oeqstepbutton_7"))
        self.oeqstepbutton_8 = QtGui.QToolButton(MainstayProcess_dialog)
        self.oeqstepbutton_8.setEnabled(True)
        self.oeqstepbutton_8.setGeometry(QtCore.QRect(10, 280, 141, 31))
        self.oeqstepbutton_8.setIcon(icon)
        self.oeqstepbutton_8.setIconSize(QtCore.QSize(20, 20))
        self.oeqstepbutton_8.setCheckable(True)
        self.oeqstepbutton_8.setChecked(False)
        self.oeqstepbutton_8.setAutoRepeat(False)
        self.oeqstepbutton_8.setAutoExclusive(False)
        self.oeqstepbutton_8.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.oeqstepbutton_8.setAutoRaise(False)
        self.oeqstepbutton_8.setArrowType(QtCore.Qt.NoArrow)
        self.oeqstepbutton_8.setObjectName(_fromUtf8("oeqstepbutton_8"))
        self.oeqstepbutton_9 = QtGui.QToolButton(MainstayProcess_dialog)
        self.oeqstepbutton_9.setEnabled(True)
        self.oeqstepbutton_9.setGeometry(QtCore.QRect(10, 330, 141, 31))
        self.oeqstepbutton_9.setIcon(icon)
        self.oeqstepbutton_9.setIconSize(QtCore.QSize(20, 20))
        self.oeqstepbutton_9.setCheckable(True)
        self.oeqstepbutton_9.setChecked(False)
        self.oeqstepbutton_9.setAutoRepeat(False)
        self.oeqstepbutton_9.setAutoExclusive(False)
        self.oeqstepbutton_9.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.oeqstepbutton_9.setAutoRaise(False)
        self.oeqstepbutton_9.setArrowType(QtCore.Qt.NoArrow)
        self.oeqstepbutton_9.setObjectName(_fromUtf8("oeqstepbutton_9"))
        self.oeqstepbutton_10 = QtGui.QToolButton(MainstayProcess_dialog)
        self.oeqstepbutton_10.setEnabled(True)
        self.oeqstepbutton_10.setGeometry(QtCore.QRect(10, 380, 141, 31))
        self.oeqstepbutton_10.setIcon(icon)
        self.oeqstepbutton_10.setIconSize(QtCore.QSize(20, 20))
        self.oeqstepbutton_10.setCheckable(True)
        self.oeqstepbutton_10.setChecked(False)
        self.oeqstepbutton_10.setAutoRepeat(False)
        self.oeqstepbutton_10.setAutoExclusive(False)
        self.oeqstepbutton_10.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.oeqstepbutton_10.setAutoRaise(False)
        self.oeqstepbutton_10.setArrowType(QtCore.Qt.NoArrow)
        self.oeqstepbutton_10.setObjectName(_fromUtf8("oeqstepbutton_10"))
        self.label = QtGui.QLabel(MainstayProcess_dialog)
        self.label.setGeometry(QtCore.QRect(10, 70, 31, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 30, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 30, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 69, 69))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.label.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(MainstayProcess_dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 151, 31, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 30, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 30, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 69, 69))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.label_2.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(MainstayProcess_dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 311, 31, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 30, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 30, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 69, 69))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.label_3.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setScaledContents(False)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(MainstayProcess_dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 261, 31, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 30, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 30, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 69, 69))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.label_4.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setScaledContents(False)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(MainstayProcess_dialog)
        self.label_5.setGeometry(QtCore.QRect(10, 365, 31, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 30, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 30, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 69, 69))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.label_5.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setScaledContents(False)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))

        self.retranslateUi(MainstayProcess_dialog)
        self.process_page.setCurrentIndex(1)
        QtCore.QObject.connect(self.project_basics_btn, QtCore.SIGNAL(_fromUtf8("clicked()")), MainstayProcess_dialog.update)
        QtCore.QObject.connect(self.investigation_area_btn, QtCore.SIGNAL(_fromUtf8("clicked()")), MainstayProcess_dialog.update)
        QtCore.QObject.connect(self.building_shapes_btn, QtCore.SIGNAL(_fromUtf8("clicked()")), MainstayProcess_dialog.update)
        QtCore.QMetaObject.connectSlotsByName(MainstayProcess_dialog)

    def retranslateUi(self, MainstayProcess_dialog):
        MainstayProcess_dialog.setWindowTitle(_translate("MainstayProcess_dialog", "Open eQuarter Workflow Utility", None))
        self.ol_plugin_installed_chckBox.setText(_translate("MainstayProcess_dialog", "Install the Open Street Map Plugin", None))
        self.project_created_chckBox.setText(_translate("MainstayProcess_dialog", "Create a new project and save it.", None))
        self.osm_layer_loaded_chckBox.setText(_translate("MainstayProcess_dialog", "Open an Open Layers Map", None))
        self.textBrowser.setHtml(_translate("MainstayProcess_dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Das ist das Haus vom Nikolaus.</p></body></html>", None))
        self.project_basics_btn.setText(_translate("MainstayProcess_dialog", "Project Basics", None))
        self.investigation_area_btn.setText(_translate("MainstayProcess_dialog", "Investigation Area", None))
        self.building_shapes_btn.setText(_translate("MainstayProcess_dialog", "Building Shapes", None))
        self.oeqstepbutton_4.setText(_translate("MainstayProcess_dialog", "Sampling Points", None))
        self.oeqstepbutton_5.setText(_translate("MainstayProcess_dialog", "Information Layers", None))
        self.oeqstepbutton_6.setText(_translate("MainstayProcess_dialog", "Legend Assignment", None))
        self.oeqstepbutton_7.setText(_translate("MainstayProcess_dialog", "Algorithm Assignment", None))
        self.oeqstepbutton_8.setText(_translate("MainstayProcess_dialog", "Building Calculations", None))
        self.oeqstepbutton_9.setText(_translate("MainstayProcess_dialog", "Quarter Valuation", None))
        self.oeqstepbutton_10.setText(_translate("MainstayProcess_dialog", "Transfer to Database", None))
        self.label.setText(_translate("MainstayProcess_dialog", "⬇︎", None))
        self.label_2.setText(_translate("MainstayProcess_dialog", "⬇︎", None))
        self.label_3.setText(_translate("MainstayProcess_dialog", "⬇︎", None))
        self.label_4.setText(_translate("MainstayProcess_dialog", "⬇︎", None))
        self.label_5.setText(_translate("MainstayProcess_dialog", "⬇︎", None))

import resources_rc
