# OeQ autogenerated correlation for 'Buildings built in correlation to year of construction'

import math
import numpy as np
def age_distribution_by_average_year_of_construction(xin,mode='distribution'):

    # OeQ autogenerated correlation for 'Buildings with housing built before 1919'
    Const= 23297.5277473
    a=     -48.9139494217
    b=     0.0385336953115
    c=     -1.34969984164e-05
    d=     1.77322275182e-09
    x=xin
    BLD_AGE1_BEFORE1919 = Const + a*x + b*x**2 + c*x**3 + d*x**4
    # OeQ autogenerated correlation for 'Buildings with housing built between 1919 and 1949'
    Const= 50973.7200178
    a=     -106.699640155
    b=     0.0837001916846
    c=     -2.91624778509e-05
    d=     3.80778936811e-09
    x=xin
    BLD_AGE1_1919TO1949 = Const + a*x + b*x**2 + c*x**3 + d*x**4
    # OeQ autogenerated correlation for 'Buildings with housing built between 1950 and 1959'
    Const= -37403.9261693
    a=     78.7804828234
    b=     -0.0622147356564
    c=     2.18334528439e-05
    d=     -2.87286104536e-09
    x=xin
    BLD_AGE1_1950TO1959 = Const + a*x + b*x**2 + c*x**3 + d*x**4
    # OeQ autogenerated correlation for 'Buildings with housing built between 1960 and 1969'
    Const= -83340.5755874
    a=     174.712061288
    b=     -0.137321334474
    c=     4.7960661162e-05
    d=     -6.28022091587e-09
    x=xin
    BLD_AGE1_1960TO1969 = Const + a*x + b*x**2 + c*x**3 + d*x**4
    # OeQ autogenerated correlation for 'Buildings with housing built between 1970 and 1979'
    Const= -134667.935697
    a=      281.76103423
    b=     -0.221026338644
    c=     7.70437777351e-05
    d=     -1.00686905487e-08
    x=xin
    BLD_AGE1_1970TO1979 = Const + a*x + b*x**2 + c*x**3 + d*x**4
    # OeQ autogenerated correlation for 'Buildings with housing built between 1980 and 1989'
    Const= -51509.501155
    a=     107.223807057
    b=     -0.0836853928984
    c=     2.90231664986e-05
    d=     -3.77385893868e-09
    x=xin
    BLD_AGE1_1980TO1989 = Const + a*x + b*x**2 + c*x**3 + d*x**4
    # OeQ autogenerated correlation for 'Buildings with housing built between 1990 and 1999'
    Const= 284609.159271
    a=     -595.093387735
    b=     0.466532619836
    c=     -0.000162527345134
    d=     2.12291702116e-08
    x=xin
    BLD_AGE1_1990TO1999 = Const + a*x + b*x**2 + c*x**3 + d*x**4
    # OeQ autogenerated correlation for 'Buildings with housing built between 2000 and 2005'
    Const= -72.878043463
    a=     0.122555663487
    b=     -6.88083483872e-05
    c=     1.28949014308e-08
    x=xin
    BLD_AGE1_2000TO2005 = Const + a*x + b*x**2 + c*x**3
    # OeQ autogenerated correlation for 'Buildings with housing built after 2005'
    Const=  717.66198743
    a=     -190.776856047
    b=     12.6785974716
    c=                 0
    d=                 0
    x=xin
    x=math.log(x)
    BLD_AGE1_AFTER2006 = Const + a*x + b*x**2 + c*x**3 + d*x**4
 
    l_sum = BLD_AGE1_BEFORE1919 + BLD_AGE1_1919TO1949 + BLD_AGE1_1950TO1959 + BLD_AGE1_1960TO1969 + BLD_AGE1_1970TO1979 + BLD_AGE1_1980TO1989 + BLD_AGE1_1990TO1999 + BLD_AGE1_2000TO2005 + BLD_AGE1_AFTER2006
    if mode is 'distribution':
        return {'BLD_AGE1_BEFORE1919' : BLD_AGE1_BEFORE1919/l_sum, 'BLD_AGE1_1919TO1949' : BLD_AGE1_1919TO1949/l_sum, 'BLD_AGE1_1950TO1959' : BLD_AGE1_1950TO1959/l_sum, 'BLD_AGE1_1960TO1969' : BLD_AGE1_1960TO1969/l_sum, 'BLD_AGE1_1970TO1979' : BLD_AGE1_1970TO1979/l_sum, 'BLD_AGE1_1980TO1989' : BLD_AGE1_1980TO1989/l_sum, 'BLD_AGE1_1990TO1999' : BLD_AGE1_1990TO1999/l_sum, 'BLD_AGE1_2000TO2005' : BLD_AGE1_2000TO2005/l_sum, 'BLD_AGE1_AFTER2006' : BLD_AGE1_AFTER2006/l_sum}

    return(BLD_AGE1_BEFORE1919/l_sum * 1 + BLD_AGE1_1919TO1949/l_sum * 1 + BLD_AGE1_1950TO1959/l_sum * 1 + BLD_AGE1_1960TO1969/l_sum * 1 + BLD_AGE1_1970TO1979/l_sum * 1 + BLD_AGE1_1980TO1989/l_sum * 1 + BLD_AGE1_1990TO1999/l_sum * 1 + BLD_AGE1_2000TO2005/l_sum * 1 + BLD_AGE1_AFTER2006/l_sum * 1 )


