# OeQ autogenerated correlation for 'Age distribution in correlation to average year of construction'

import math
import numpy as np
def age_distribution_by_average_year_of_construction(xin,mode='distribution'):

    # OeQ autogenerated correlation for 'Buildings with housing built before 1919'
    Const= 17305.6055113
    a=     -36.3881499767
    b=     0.0287164086005
    c=     -1.00779128691e-05
    d=     1.32677126018e-09
    x=xin
    BLD_AGE1_BEFORE1919 = Const + a*x + b*x**2 + c*x**3 + d*x**4
    # OeQ autogenerated correlation for 'Buildings with housing built between 1919 and 1949'
    Const= 35569.8677831
    a=     -74.5130920293
    b=     0.0584852319919
    c=     -2.03850586481e-05
    d=     2.66224063943e-09
    x=xin
    BLD_AGE1_1919TO1949 = Const + a*x + b*x**2 + c*x**3 + d*x**4
    # OeQ autogenerated correlation for 'Buildings with housing built between 1950 and 1959'
    Const=  19634.851143
    a=     -40.3139110208
    b=     0.0310158404272
    c=     -1.0597324233e-05
    d=     1.35676404023e-09
    x=xin
    BLD_AGE1_1950TO1959 = Const + a*x + b*x**2 + c*x**3 + d*x**4
    # OeQ autogenerated correlation for 'Buildings with housing built between 1960 and 1969'
    Const= 1565.83829057
    a=     -2.45714853733
    b=     0.00128442363581
    c=     -2.2364578333e-07
    x=xin
    BLD_AGE1_1960TO1969 = Const + a*x + b*x**2 + c*x**3
    # OeQ autogenerated correlation for 'Buildings with housing built between 1970 and 1979'
    Const= -13807.4794397
    a=     29.4456917826
    b=     -0.0235344705472
    c=     8.3548190733e-06
    d=     -1.11152868813e-09
    x=xin
    BLD_AGE1_1970TO1979 = Const + a*x + b*x**2 + c*x**3 + d*x**4
    # OeQ autogenerated correlation for 'Buildings with housing built between 1980 and 1989'
    Const= -30975.4127214
    a=     64.4257617573
    b=     -0.0502414455583
    c=     1.74102147726e-05
    d=     -2.26199334127e-09
    x=xin
    BLD_AGE1_1980TO1989 = Const + a*x + b*x**2 + c*x**3 + d*x**4
    # OeQ autogenerated correlation for 'Buildings with housing built between 1990 and 1999'
    Const= -78927.6111133
    a=     163.688015644
    b=     -0.127255654658
    c=     4.39532475707e-05
    d=     -5.69071518752e-09
    x=xin
    BLD_AGE1_1990TO1999 = Const + a*x + b*x**2 + c*x**3 + d*x**4
    # OeQ autogenerated correlation for 'Buildings with housing built between 2000 and 2005'
    Const= 11766.6009045
    a=     -24.6792191619
    b=     0.0194109659543
    c=     -6.78574716302e-06
    d=     8.89633599806e-10
    x=xin
    BLD_AGE1_2000TO2005 = Const + a*x + b*x**2 + c*x**3 + d*x**4
    # OeQ autogenerated correlation for 'Buildings with housing built after 2005'
    Const= 44628.2541018
    a=     -93.1984482031
    b=     0.0729744813998
    c=     -2.53912946008e-05
    d=     3.31257598651e-09
    x=xin
    BLD_AGE1_AFTER2006 = Const + a*x + b*x**2 + c*x**3 + d*x**4
 
    l_sum = BLD_AGE1_BEFORE1919 + BLD_AGE1_1919TO1949 + BLD_AGE1_1950TO1959 + BLD_AGE1_1960TO1969 + BLD_AGE1_1970TO1979 + BLD_AGE1_1980TO1989 + BLD_AGE1_1990TO1999 + BLD_AGE1_2000TO2005 + BLD_AGE1_AFTER2006
    if mode is 'distribution':
        return {'BLD_AGE1_BEFORE1919' : BLD_AGE1_BEFORE1919/l_sum, 'BLD_AGE1_1919TO1949' : BLD_AGE1_1919TO1949/l_sum, 'BLD_AGE1_1950TO1959' : BLD_AGE1_1950TO1959/l_sum, 'BLD_AGE1_1960TO1969' : BLD_AGE1_1960TO1969/l_sum, 'BLD_AGE1_1970TO1979' : BLD_AGE1_1970TO1979/l_sum, 'BLD_AGE1_1980TO1989' : BLD_AGE1_1980TO1989/l_sum, 'BLD_AGE1_1990TO1999' : BLD_AGE1_1990TO1999/l_sum, 'BLD_AGE1_2000TO2005' : BLD_AGE1_2000TO2005/l_sum, 'BLD_AGE1_AFTER2006' : BLD_AGE1_AFTER2006/l_sum}

    return(BLD_AGE1_BEFORE1919/l_sum * 1850 + BLD_AGE1_1919TO1949/l_sum * 1935 + BLD_AGE1_1950TO1959/l_sum * 1954.5 + BLD_AGE1_1960TO1969/l_sum * 1964.5 + BLD_AGE1_1970TO1979/l_sum * 1974.5 + BLD_AGE1_1980TO1989/l_sum * 1984.5 + BLD_AGE1_1990TO1999/l_sum * 1994.5 + BLD_AGE1_2000TO2005/l_sum * 2002.5 + BLD_AGE1_AFTER2006/l_sum * 2050 )


