# OeQ autogenerated correlation function: Building Density in Correlation to the Population Density
building_density_by_population_density<-function(xin,mode='distribution',...){
x=xin

# OeQ autogenerated correlation for 'Density of buildings'
BLD_DENS = lookup(correlation(Const = 3.01748429716721,a = 0.289651885019723,b = -6.37219457944504e-05,c = 6.06666442362151e-09,d = 3.01748429716721),x)
#l.sum = BLD_DENS
 if(mode=='distribution'){
return(list(BLD_DENS = lookup.correlation(BLD_DENS,x)/l.sum))
}
return(BLD_DENS/l.sum * 1850 )
}

