# OeQ autogenerated correlation for 'Living Area in a Building in Correlation to the Portion of 2-Flat-Buildings'

import math
import numpy as np
import oeqCorrelation as oeq
def get(*xin):

    # OeQ autogenerated correlation for 'Total Living Area of all Flats of a Building'
    TOTAL_LIVING_AREA= oeq.correlation(
    const= 139.567020214,
    a=     440.928668012,
    b=     -1536.74490891,
    c=     1613.73238622,
    mode= "lin")

    return dict(TOTAL_LIVING_AREA=TOTAL_LIVING_AREA.lookup(*xin))

