# OeQ autogenerated correlation for 'Number of Common walls in Correlation to population density '

import math
import numpy as np
import oeqCorrelation as oeq
def get(*xin):

    # OeQ autogenerated correlation for 'Average Number of Common Walls per Flat'
    FLT_COMWALL_AVG= oeq.correlation(
    const= 0.0844256206669,
    a=     0.509345407415,
    b=     -0.224269236005,
    c=     0.0342874642335,
    d=     -0.00146672896543,
    mode= "log")

    return FLT_COMWALL_AVG.lookup(*xin)

print get(1956)
