# OeQ autogenerated correlation for 'Buildings with n flats in correlation to population density'

import math
import numpy as np
from . import oeqCorrelation as oeq
def distribution_by_population_density(*xin):

    # OeQ autogenerated correlation for 'Buildings with housing with 1 flat'
    BLD_NOFLAT_1= oeq.correlation(
    const= 1.07781959235,
    a=     -0.191560414505,
    b=     0.0390092507965,
    c=     -0.00297387956953,
    mode= "log")
    # OeQ autogenerated correlation for 'Buildings with housing with 2 flats'
    BLD_NOFLAT_2= oeq.correlation(
    const= -0.105048021492,
    a=     0.172471300374,
    b=     -0.0385246868012,
    c=     0.00427310573784,
    d=     -0.000213769103587,
    mode= "log")
    # OeQ autogenerated correlation for 'Buildings with housing with 3 up to 6 flats'
    BLD_NOFLAT_3TO6= oeq.correlation(
    const= 0.0401278689213,
    a=     0.0101662719166,
    b=     -0.00362339425514,
    c=     0.000599342447601,
    mode= "log")
    # OeQ autogenerated correlation for 'Buildings with housing with 7 up to 12 flats'
    BLD_NOFLAT_7TO12= oeq.correlation(
    const= 0.0226413988451,
    a=     -0.0354053279534,
    b=     0.018012257139,
    c=     -0.00356706888547,
    d=     0.000257056615638,
    mode= "log")
    # OeQ autogenerated correlation for 'Buildings with housing with more than 13 flats'
    BLD_NOFLAT_MTH13= oeq.correlation(
    const= 0.0219670735062,
    a=     -0.0328764453965,
    b=     0.0162840430352,
    c=     -0.00314225243169,
    d=     0.000207327056984,
    mode= "log")

    return dict(BLD_NOFLAT_1=BLD_NOFLAT_1.lookup(*xin),
    BLD_NOFLAT_2=BLD_NOFLAT_2.lookup(*xin),
    BLD_NOFLAT_3TO6=BLD_NOFLAT_3TO6.lookup(*xin),
    BLD_NOFLAT_7TO12=BLD_NOFLAT_7TO12.lookup(*xin),
    BLD_NOFLAT_MTH13=BLD_NOFLAT_MTH13.lookup(*xin))

