# OeQ autogenerated correlation function: Buildings with n flats in Correlation to Building Age
distribution_by_building_age<-function(xin,mode='distribution',...){
x=xin

# OeQ autogenerated correlation for 'Buildings with housing built before 1919'
BLD_AGE1_BEFORE1919 = correlation(Const = 0.218400796288133,a = 0.139917684806745,b = -0.0785669704040057,c = 0.0128751958504777,d = -0.000718650545766326,mode="log")
x=xin

# OeQ autogenerated correlation for 'Buildings with housing built between 1919 and 1949'
BLD_AGE1_1919TO1949 = correlation(Const = 0.0644891868718919,a = 0.182649511028362,b = -0.106844353701011,c = 0.021303714473234,d = -0.00138131054125817,mode="log")
x=xin

# OeQ autogenerated correlation for 'Buildings with housing built between 1950 and 1959'
BLD_AGE1_1950TO1959 = correlation(Const = 0.127831050080894,a = 0.0408430239782051,b = -0.0584209845192708,c = 0.0168252937237003,d = -0.00137497666598905,mode="log")
x=xin

# OeQ autogenerated correlation for 'Buildings with housing built between 1960 and 1969'
BLD_AGE1_1960TO1969 = correlation(Const = 0.134706345959842,a = -0.0520577733636552,b = 0.0200888538715975,c = -0.00178165590979193,d = -2.82105377068519e-06,mode="log")
x=xin

# OeQ autogenerated correlation for 'Buildings with housing built between 1970 and 1979'
BLD_AGE1_1970TO1979 = correlation(Const = 0.0221346390276663,a = 0.0557894906948728,b = -0.0076480037273803,c = 0.000382311836650455,d = 0.0221346390276663,mode="log")
x=xin

# OeQ autogenerated correlation for 'Buildings with housing built between 1980 and 1989'
BLD_AGE1_1980TO1989 = correlation(Const = 0.0990214523453397,a = -0.0609377303998566,b = 0.041696251869161,c = -0.00846690659304837,d = 0.000550074280717096,mode="log")
x=xin

# OeQ autogenerated correlation for 'Buildings with housing built between 1990 and 1999'
BLD_AGE1_1990TO1999 = correlation(Const = 0.17040533125914,a = -0.000498522782844011,b = 1.25570349845628e-06,c = -8.66097165610714e-10,d = 0.17040533125914,mode="lin")
x=xin

# OeQ autogenerated correlation for 'Buildings with housing built between 2000 and 2005'
BLD_AGE1_2000TO2005 = correlation(Const = 0.00674760685013732,a = 0.0363678151300798,b = -0.00148432910402898,c = -0.00160371729722616,d = 0.00019290788541471,mode="log")
x=xin

# OeQ autogenerated correlation for 'Buildings with housing built after 2005'
BLD_AGE1_AFTER2006 = correlation(Const = 0.00335451269838553,a = 0.0113925363266493,b = 0.00140565464100774,c = -0.000971145268108499,d = 9.92754910252037e-05,mode="log")
 
l.sum = BLD_AGE1_BEFORE1919 + BLD_AGE1_1919TO1949 + BLD_AGE1_1950TO1959 + BLD_AGE1_1960TO1969 + BLD_AGE1_1970TO1979 + BLD_AGE1_1980TO1989 + BLD_AGE1_1990TO1999 + BLD_AGE1_2000TO2005 + BLD_AGE1_AFTER2006
 if(mode=='distribution'){
return(list(BLD_AGE1_BEFORE1919 = BLD_AGE1_BEFORE1919/l.sum, BLD_AGE1_1919TO1949 = BLD_AGE1_1919TO1949/l.sum, BLD_AGE1_1950TO1959 = BLD_AGE1_1950TO1959/l.sum, BLD_AGE1_1960TO1969 = BLD_AGE1_1960TO1969/l.sum, BLD_AGE1_1970TO1979 = BLD_AGE1_1970TO1979/l.sum, BLD_AGE1_1980TO1989 = BLD_AGE1_1980TO1989/l.sum, BLD_AGE1_1990TO1999 = BLD_AGE1_1990TO1999/l.sum, BLD_AGE1_2000TO2005 = BLD_AGE1_2000TO2005/l.sum, BLD_AGE1_AFTER2006 = BLD_AGE1_AFTER2006/l.sum))
}
return(BLD_AGE1_BEFORE1919/l.sum * 1 + BLD_AGE1_1919TO1949/l.sum * 2 + BLD_AGE1_1950TO1959/l.sum * 4.5 + BLD_AGE1_1960TO1969/l.sum * 9.5 + BLD_AGE1_1970TO1979/l.sum * 20 + BLD_AGE1_1980TO1989/l.sum * NULL + BLD_AGE1_1990TO1999/l.sum * NULL + BLD_AGE1_2000TO2005/l.sum * NULL + BLD_AGE1_AFTER2006/l.sum * NULL )
}

