# OeQ autogenerated correlation function: Buildings with n flats in correlation to population density
distribution_by_population_density<-function(xin,mode='distribution',...){
# OeQ autogenerated correlation for 'Buildings with housing with 1 flat'
BLD_NOFLAT_1 = correlation(
    Const = 1.04973644198322,
    a = -0.151469688448965,
    b = 0.0210688033972109,
    c = 0.000288178235459953,
    d = -0.00020532195800135,
    mode="log")

# OeQ autogenerated correlation for 'Buildings with housing with 2 flats'
BLD_NOFLAT_2 = correlation(
    Const = -0.0268737715823538,
    a = 0.0894154067354349,
    b = -0.00883730566807948,
    c = -9.09246219414377e-06,
    d = -0.0268737715823538,
    mode="log")

# OeQ autogenerated correlation for 'Buildings with housing with 3 up to 6 flats'
BLD_NOFLAT_3TO6 = correlation(
    Const = -0.0125526276601867,
    a = 0.061871999412803,
    b = -0.0212407344719959,
    c = 0.00291764904325337,
    d = -9.77157800229998e-05,
    mode="log")

# OeQ autogenerated correlation for 'Buildings with housing with 7 up to 12 flats'
BLD_NOFLAT_7TO12 = correlation(
    Const = 0.0217514712675724,
    a = -0.0365396921989058,
    b = 0.0192926288569412,
    c = -0.00388638817630075,
    d = 0.000280350342123904,
    mode="log")

# OeQ autogenerated correlation for 'Buildings with housing with more than 13 flats'
BLD_NOFLAT_MTH13 = correlation(
    Const = 0.0238167058916476,
    a = -0.0378671564775172,
    b = 0.0187629594468159,
    c = -0.00356877043080594,
    d = 0.000231111367082915,
    mode="log")

 # Looking up valuesx=xin
BLD_NOFLAT_1 = lookup(BLD_NOFLAT_1,x)

x=xin
BLD_NOFLAT_2 = lookup(BLD_NOFLAT_2,x)

x=xin
BLD_NOFLAT_3TO6 = lookup(BLD_NOFLAT_3TO6,x)

x=xin
BLD_NOFLAT_7TO12 = lookup(BLD_NOFLAT_7TO12,x)

x=xin
BLD_NOFLAT_MTH13 = lookup(BLD_NOFLAT_MTH13,x)

 
l.sum = BLD_NOFLAT_1 + BLD_NOFLAT_2 + BLD_NOFLAT_3TO6 + BLD_NOFLAT_7TO12 + BLD_NOFLAT_MTH13
 if(mode=='distribution'){
return(data.frame(BLD_NOFLAT_1 = BLD_NOFLAT_1/l.sum, BLD_NOFLAT_2 = BLD_NOFLAT_2/l.sum, BLD_NOFLAT_3TO6 = BLD_NOFLAT_3TO6/l.sum, BLD_NOFLAT_7TO12 = BLD_NOFLAT_7TO12/l.sum, BLD_NOFLAT_MTH13 = BLD_NOFLAT_MTH13/l.sum),stringsAsFactors=FALSE)
}
return(BLD_NOFLAT_1/l.sum * 1 + BLD_NOFLAT_2/l.sum * 2 + BLD_NOFLAT_3TO6/l.sum * 4.5 + BLD_NOFLAT_7TO12/l.sum * 9.5 + BLD_NOFLAT_MTH13/l.sum * 20 )
}

