# OeQ autogenerated correlation function: Buildings with n flats in Correlation to Building Density
distribution_by_building_density<-function(xin,mode='distribution',...){
x=xin

# OeQ autogenerated correlation for 'Buildings with housing with 1 flat'
BLD_NOFLAT_1 = correlation(Const = 0.954294194851301,a = -0.118372593898808,b = 0.0101143605579372,c = 0.00230528027057095,d = -0.000325919892959496,mode="log")
x=xin

# OeQ autogenerated correlation for 'Buildings with housing with 2 flats'
BLD_NOFLAT_2 = correlation(Const = 0.0329079238398878,a = 0.107348532653513,b = -0.0205425487326784,c = 0.000937293415838084,d = 0.0329079238398878,mode="log")
x=xin

# OeQ autogenerated correlation for 'Buildings with housing with 3 up to 6 flats'
BLD_NOFLAT_3TO6 = correlation(Const = 0.0132776550643335,a = 0.0156086833510214,b = 0.00318674473518144,c = -0.00111257009899344,d = 0.000108084594937774,mode="log")
x=xin

# OeQ autogenerated correlation for 'Buildings with housing with 7 up to 12 flats'
BLD_NOFLAT_7TO12 = correlation(Const = -0.00391229556365063,a = 0.017533221099674,b = -0.00790631811746792,c = 0.00107405562317084,d = -0.00391229556365063,mode="log")
x=xin

# OeQ autogenerated correlation for 'Buildings with housing with more than 13 flats'
BLD_NOFLAT_MTH13 = correlation(Const = -0.00240657589737173,a = 0.010866313828451,b = -0.00528042770113708,c = 0.000652133734208117,d = -0.00240657589737173,mode="log")
 
l.sum = BLD_NOFLAT_1 + BLD_NOFLAT_2 + BLD_NOFLAT_3TO6 + BLD_NOFLAT_7TO12 + BLD_NOFLAT_MTH13
 if(mode=='distribution'){
return(list(BLD_NOFLAT_1 = BLD_NOFLAT_1/l.sum, BLD_NOFLAT_2 = BLD_NOFLAT_2/l.sum, BLD_NOFLAT_3TO6 = BLD_NOFLAT_3TO6/l.sum, BLD_NOFLAT_7TO12 = BLD_NOFLAT_7TO12/l.sum, BLD_NOFLAT_MTH13 = BLD_NOFLAT_MTH13/l.sum))
}
return(BLD_NOFLAT_1/l.sum * 1 + BLD_NOFLAT_2/l.sum * 2 + BLD_NOFLAT_3TO6/l.sum * 4.5 + BLD_NOFLAT_7TO12/l.sum * 9.5 + BLD_NOFLAT_MTH13/l.sum * 20 )
}

