# OeQ autogenerated correlation for 'Living Area in a Building in Correlation to the Portion of Buildings with 3 to 6 Flats'

import math
import numpy as np
import oeqCorrelation as oeq
def get(*xin):

    # OeQ autogenerated correlation for 'Total Living Area of all Flats of a Building'
    TOTAL_LIVING_AREA= oeq.correlation(
    const= 170.892227121,
    a=     5.50987585061,
    b=     -0.000228398571373,
    c=     -0.000119754558792,
    mode= "lin")

    return dict(TOTAL_LIVING_AREA=TOTAL_LIVING_AREA.lookup(*xin))

