# OeQ autogenerated correlation for 'testfunctioncorr'

import math
import numpy as np
import oeqCorrelation as oeq
def testfunctioncorr(xin,mode='distribution'):

    # OeQ autogenerated correlation for 'NULL'
    BLD_NOFLAT_1= oeq.correlation(
    const= 0.954294194851,
    a=     -0.118372593899,
    b=     0.0101143605579,
    c=     0.00230528027057,
    d=     -0.000325919892959,
    mode= "log")
    # OeQ autogenerated correlation for 'NULL'
    BLD_NOFLAT_2= oeq.correlation(
    const= 0.0329079238399,
    a=     0.107348532654,
    b=     -0.0205425487327,
    c=     0.000937293415838,
    mode= "log")
    # OeQ autogenerated correlation for 'NULL'
    BLD_NOFLAT_3TO6= oeq.correlation(
    const= 0.0132776550643,
    a=     0.015608683351,
    b=     0.00318674473518,
    c=     -0.00111257009899,
    d=     0.000108084594938,
    mode= "log")
    # OeQ autogenerated correlation for 'NULL'
    BLD_NOFLAT_7TO12= oeq.correlation(
    const= -0.00391229556365,
    a=     0.0175332210997,
    b=     -0.00790631811747,
    c=     0.00107405562317,
    mode= "log")
    # OeQ autogenerated correlation for 'NULL'
    BLD_NOFLAT_MTH13= oeq.correlation(
    const= -0.00240657589737,
    a=     0.0108663138285,
    b=     -0.00528042770114,
    c=     0.000652133734208,
    mode= "log")

    return dict(BLD_NOFLAT_1=BLD_NOFLAT_1.lookup(xin)BLD_NOFLAT_2=BLD_NOFLAT_2.lookup(xin)BLD_NOFLAT_3TO6=BLD_NOFLAT_3TO6.lookup(xin)BLD_NOFLAT_7TO12=BLD_NOFLAT_7TO12.lookup(xin)BLD_NOFLAT_MTH13=BLD_NOFLAT_MTH13.lookup(xin)
print testfunctioncorr(1500)
