# OeQ autogenerated correlation for 'Window/Wall Ratio South in Correlation to the Building Age'

import math
import numpy as np
import oeqCorrelation as oeq
def window_wall_ratio_south_AVG_by_building_age_correlation(*xin):

    # OeQ autogenerated correlation for 'Window to Wall Ratio in Southern Direction'
    A_WIN_S_BY_AW= oeq.correlation(
    const= 10168.4679085,
    a=     -20.8133662361,
    b=     0.0159674047391,
    c=     -5.44156257373e-06,
    d=     6.95077881528e-10,
    mode= "lin")

    return dict(A_WIN_S_BY_AW=A_WIN_S_BY_AW.lookup(*xin))

