# OeQ autogenerated correlation for 'Window/Wall Ratio East in Correlation to the Building Age'

import math
import numpy as np
import oeqCorrelation as oeq
def window_wall_east_ratio_MFH_by_building_age_correlation(*xin):

    # OeQ autogenerated correlation for 'Window to Wall Ratio in Eastern Direction'
    A_WIN_E_BY_AW= oeq.correlation(
    const= -37846.911859,
    a=     77.3456608212,
    b=     -0.0592490161432,
    c=     2.01631207341e-05,
    d=     -2.57207834473e-09,
    mode= "lin")

    return dict(A_WIN_E_BY_AW=A_WIN_E_BY_AW.lookup(*xin))

