# OeQ autogenerated correlation for 'Window/Wall Ratio in Correlation to the Building Age'

import math
import numpy as np
import oeqCorrelation as oeq
def window_wall_ratio_SFH_by_building_age_correlation(*xin):

    # OeQ autogenerated correlation for 'Window to Wall Ratio in all Directions'
    A_WIN_BY_AW= oeq.correlation(
    const= 31395.5662123,
    a=     -64.2747328811,
    b=     0.0493180059638,
    c=     -1.68093075787e-05,
    d=     2.14728207545e-09,
    mode= "lin")

    return dict(A_WIN_BY_AW=A_WIN_BY_AW.lookup(*xin))

