# OeQ autogenerated correlation for 'Window U-Value in correlation to average year of construction'

import math
import numpy as np
def window_uvalue_by_average_year_of_construction(xin,mode='distribution'):

    # OeQ autogenerated correlation for 'NULL'
    Const= 134018.479698
    a=     -278.704659837
    b=     0.21708954443
    c=     -7.50573532193e-05
    d=     9.71836580667e-09
    x=xin
    UVAL_WIN = Const + a*x + b*x**2 + c*x**3 + d*x**4
    # OeQ autogenerated correlation for 'NULL'
    Const= 120046.968215
    a=     -249.82114301
    b=     0.194718483741
    c=     -6.73636413768e-05
    d=     8.72705641799e-09
    x=xin
    l.investigation$.regressions$UVAL_WIN$.smoothsplinelog$.predict(WINDOW_UVALUE$YEAR)$y = Const + a*x + b*x**2 + c*x**3 + d*x**4
 
    l_sum = UVAL_WIN + l.investigation$.regressions$UVAL_WIN$.smoothsplinelog$.predict(WINDOW_UVALUE$YEAR)$y
    if mode is 'distribution':
        return {'UVAL_WIN' : UVAL_WIN/l_sum, 'l.investigation$.regressions$UVAL_WIN$.smoothsplinelog$.predict(WINDOW_UVALUE$YEAR)$y' : l.investigation$.regressions$UVAL_WIN$.smoothsplinelog$.predict(WINDOW_UVALUE$YEAR)$y/l_sum}

    return(UVAL_WIN/l_sum * 1850 + l.investigation$.regressions$UVAL_WIN$.smoothsplinelog$.predict(WINDOW_UVALUE$YEAR)$y/l_sum * 1935 )


