# OeQ autogenerated correlation function: Window/Wall Ratio in Correlation to the Building Age
window_wall_ratio_by_building_age1<-function(xin,mode='distribution',...){
# OeQ autogenerated correlation for 'Window to Wall Ratio in Eastern Direction'
A_WIN_E_BY_AW = correlation(
    Const = -11052.3823843454,
    a = 22.6351382938075,
    b = -0.0173766908244037,
    c = 5.92660035179237e-06,
    d = -7.57742893580664e-10,
    mode="lin")

# OeQ autogenerated correlation for 'Window to Wall Ratio in Southern Direction'
A_WIN_S_BY_AW = correlation(
    Const = 10302.313664394,
    a = -21.0920719949802,
    b = 0.0161850186845981,
    c = -5.5170720356786e-06,
    d = 7.04901928915662e-10,
    mode="lin")

# OeQ autogenerated correlation for 'Window to Wall Ratio in Western Direction'
A_WIN_W_BY_AW = correlation(
    Const = -10943.0054912675,
    a = 22.4107483922506,
    b = -0.0172041943831203,
    c = 5.86771158801451e-06,
    d = -7.50209970419744e-10,
    mode="lin")

# OeQ autogenerated correlation for 'Window to Wall Ratio in Northern Direction'
A_WIN_N_BY_AW = correlation(
    Const = 6714.12158412741,
    a = -13.7979342400397,
    b = 0.0106277696953726,
    c = -3.63627735373951e-06,
    d = 4.66308256101437e-10,
    mode="lin")

# OeQ autogenerated correlation for 'Window to Wall Ratio in all Directions'
A_WIN_BY_AW = correlation(
    Const = -5192.18309207001,
    a = 10.5955843529566,
    b = -0.00810791696619307,
    c = 2.7576170725279e-06,
    d = -3.51750993301691e-10,
    mode="lin")

 # Looking up valuesx=xin
A_WIN_E_BY_AW = lookup(A_WIN_E_BY_AW,x)

x=xin
A_WIN_S_BY_AW = lookup(A_WIN_S_BY_AW,x)

x=xin
A_WIN_W_BY_AW = lookup(A_WIN_W_BY_AW,x)

x=xin
A_WIN_N_BY_AW = lookup(A_WIN_N_BY_AW,x)

x=xin
A_WIN_BY_AW = lookup(A_WIN_BY_AW,x)

 
l.sum = A_WIN_E_BY_AW + A_WIN_S_BY_AW + A_WIN_W_BY_AW + A_WIN_N_BY_AW + A_WIN_BY_AW
 if(mode=='distribution'){
return(data.frame(A_WIN_E_BY_AW = A_WIN_E_BY_AW/l.sum, A_WIN_S_BY_AW = A_WIN_S_BY_AW/l.sum, A_WIN_W_BY_AW = A_WIN_W_BY_AW/l.sum, A_WIN_N_BY_AW = A_WIN_N_BY_AW/l.sum, A_WIN_BY_AW = A_WIN_BY_AW/l.sum),stringsAsFactors=FALSE)
}
return(A_WIN_E_BY_AW/l.sum * 1850 + A_WIN_S_BY_AW/l.sum * 1935 + A_WIN_W_BY_AW/l.sum * 1954.5 + A_WIN_N_BY_AW/l.sum * 1964.5 + A_WIN_BY_AW/l.sum * 1974.5 )
}

