# OeQ autogenerated correlation for 'Window/Wall Ratio East in Correlation to the Building Age'

import math
import numpy as np
import oeqCorrelation as oeq
def get(*xin):

    # OeQ autogenerated correlation for 'Window to Wall Ratio in Eastern Direction'
    A_WIN_E_BY_AW= oeq.correlation(
    const= -11117.2066108,
    a=     22.7674576066,
    b=     -0.0174778241168,
    c=     5.9609029514e-06,
    d=     -7.62099304536e-10,
    mode= "lin")

    return dict(A_WIN_E_BY_AW=A_WIN_E_BY_AW.lookup(*xin))

