# OeQ autogenerated correlation function: Window/Wall Ratio at Multi Family Houses in Correlation to the Building Age
window_wall_ratio_MFH_by_building_age<-function(xin,mode='distribution',...){
# OeQ autogenerated correlation for 'Window to Wall Ratio in Eastern Direction'
A_WIN_E_BY_AW = correlation(
    Const = -36887.3474111837,
    a = 75.3645550275573,
    b = -0.0577161046534521,
    c = 1.96362693857616e-05,
    d = -2.50421507957282e-09,
    mode="lin")

# OeQ autogenerated correlation for 'Window to Wall Ratio in Southern Direction'
A_WIN_S_BY_AW = correlation(
    Const = 20056.5626230339,
    a = -41.0808701415285,
    b = 0.0315382066440263,
    c = -1.07556725786992e-05,
    d = 1.37486214954112e-09,
    mode="lin")

# OeQ autogenerated correlation for 'Window to Wall Ratio in Western Direction'
A_WIN_W_BY_AW = correlation(
    Const = -36887.3474111837,
    a = 75.3645550275573,
    b = -0.0577161046534521,
    c = 1.96362693857616e-05,
    d = -2.50421507957282e-09,
    mode="lin")

# OeQ autogenerated correlation for 'Window to Wall Ratio in Northern Direction'
A_WIN_N_BY_AW = correlation(
    Const = 13926.9395996729,
    a = -28.5763303240769,
    b = 0.0219763900267478,
    c = -7.50745126780814e-06,
    d = 9.61237974673567e-10,
    mode="lin")

# OeQ autogenerated correlation for 'Window to Wall Ratio in all Directions'
A_WIN_BY_AW = correlation(
    Const = -38379.8302692345,
    a = 78.1944364451439,
    b = -0.0597196461799462,
    c = 2.02639207706804e-05,
    d = -2.57760070410615e-09,
    mode="lin")

 # Looking up valuesx=xin
A_WIN_E_BY_AW = lookup(A_WIN_E_BY_AW,x)

x=xin
A_WIN_S_BY_AW = lookup(A_WIN_S_BY_AW,x)

x=xin
A_WIN_W_BY_AW = lookup(A_WIN_W_BY_AW,x)

x=xin
A_WIN_N_BY_AW = lookup(A_WIN_N_BY_AW,x)

x=xin
A_WIN_BY_AW = lookup(A_WIN_BY_AW,x)

 
l.sum = A_WIN_E_BY_AW + A_WIN_S_BY_AW + A_WIN_W_BY_AW + A_WIN_N_BY_AW + A_WIN_BY_AW
 if(mode=='distribution'){
return(data.frame(A_WIN_E_BY_AW = A_WIN_E_BY_AW/l.sum, A_WIN_S_BY_AW = A_WIN_S_BY_AW/l.sum, A_WIN_W_BY_AW = A_WIN_W_BY_AW/l.sum, A_WIN_N_BY_AW = A_WIN_N_BY_AW/l.sum, A_WIN_BY_AW = A_WIN_BY_AW/l.sum),stringsAsFactors=FALSE)
}
return(A_WIN_E_BY_AW/l.sum * 1850 + A_WIN_S_BY_AW/l.sum * 1935 + A_WIN_W_BY_AW/l.sum * 1954.5 + A_WIN_N_BY_AW/l.sum * 1964.5 + A_WIN_BY_AW/l.sum * 1974.5 )
}

