# OeQ autogenerated correlation function: Window/Wall Ratio at Large Multi Family Houses in Correlation to the Building Age
window_wall_ratio_LMFH_by_building_age<-function(xin,mode='distribution',...){
# OeQ autogenerated correlation for 'Window to Wall Ratio in Eastern Direction'
A_WIN_E_BY_AW = correlation(
    Const = -4387.92849644847,
    a = 8.65253784798969,
    b = -0.00638090435474296,
    c = 2.08575202233421e-06,
    d = -2.54970590400266e-10,
    mode="lin")

# OeQ autogenerated correlation for 'Window to Wall Ratio in Southern Direction'
A_WIN_S_BY_AW = correlation(
    Const = -13491.1803091324,
    a = 28.0039464509007,
    b = -0.0217846953298096,
    c = 7.52701969327676e-06,
    d = -9.74623309452955e-10,
    mode="lin")

# OeQ autogenerated correlation for 'Window to Wall Ratio in Western Direction'
A_WIN_W_BY_AW = correlation(
    Const = -4387.92849644847,
    a = 8.65253784798969,
    b = -0.00638090435474296,
    c = 2.08575202233421e-06,
    d = -2.54970590400266e-10,
    mode="lin")

# OeQ autogenerated correlation for 'Window to Wall Ratio in Northern Direction'
A_WIN_N_BY_AW = correlation(
    Const = -16601.0004915816,
    a = 34.3541788083962,
    b = -0.026644228138468,
    c = 9.17878093035055e-06,
    d = -1.18503777565065e-09,
    mode="lin")

# OeQ autogenerated correlation for 'Window to Wall Ratio in all Directions'
A_WIN_BY_AW = correlation(
    Const = -37384.3262911233,
    a = 76.624999298146,
    b = -0.0588592044321621,
    c = 2.00825771494776e-05,
    d = -2.56807721691562e-09,
    mode="lin")

 # Looking up valuesx=xin
A_WIN_E_BY_AW = lookup(A_WIN_E_BY_AW,x)

x=xin
A_WIN_S_BY_AW = lookup(A_WIN_S_BY_AW,x)

x=xin
A_WIN_W_BY_AW = lookup(A_WIN_W_BY_AW,x)

x=xin
A_WIN_N_BY_AW = lookup(A_WIN_N_BY_AW,x)

x=xin
A_WIN_BY_AW = lookup(A_WIN_BY_AW,x)

 
l.sum = A_WIN_E_BY_AW + A_WIN_S_BY_AW + A_WIN_W_BY_AW + A_WIN_N_BY_AW + A_WIN_BY_AW
 if(mode=='distribution'){
return(data.frame(A_WIN_E_BY_AW = A_WIN_E_BY_AW/l.sum, A_WIN_S_BY_AW = A_WIN_S_BY_AW/l.sum, A_WIN_W_BY_AW = A_WIN_W_BY_AW/l.sum, A_WIN_N_BY_AW = A_WIN_N_BY_AW/l.sum, A_WIN_BY_AW = A_WIN_BY_AW/l.sum),stringsAsFactors=FALSE)
}
return(A_WIN_E_BY_AW/l.sum * 1850 + A_WIN_S_BY_AW/l.sum * 1935 + A_WIN_W_BY_AW/l.sum * 1954.5 + A_WIN_N_BY_AW/l.sum * 1964.5 + A_WIN_BY_AW/l.sum * 1974.5 )
}

