# OeQ autogenerated correlation for 'Window/Wall Ratio at Large Multi Family Houses in Correlation to the Building Age'

import math
import numpy as np
def window_wall_ratio_LMFH_by_building_age(xin,mode='distribution'):

    # OeQ autogenerated correlation for 'Window to Wall Ratio in Eastern Direction'
    Const= -4387.92849645
    a=     8.65253784799
    b=     -0.00638090435474
    c=     2.08575202233e-06
    d=     -2.549705904e-10
    A_WIN_E_BY_AW = Const + a*x + b*x**2 + c*x**3 + d*x**4
    # OeQ autogenerated correlation for 'Window to Wall Ratio in Southern Direction'
    Const= -13491.1803091
    a=     28.0039464509
    b=     -0.0217846953298
    c=     7.52701969328e-06
    d=     -9.74623309453e-10
    A_WIN_S_BY_AW = Const + a*x + b*x**2 + c*x**3 + d*x**4
    # OeQ autogenerated correlation for 'Window to Wall Ratio in Western Direction'
    Const= -4387.92849645
    a=     8.65253784799
    b=     -0.00638090435474
    c=     2.08575202233e-06
    d=     -2.549705904e-10
    A_WIN_W_BY_AW = Const + a*x + b*x**2 + c*x**3 + d*x**4
    # OeQ autogenerated correlation for 'Window to Wall Ratio in Northern Direction'
    Const= -16601.0004916
    a=     34.3541788084
    b=     -0.0266442281385
    c=     9.17878093035e-06
    d=     -1.18503777565e-09
    A_WIN_N_BY_AW = Const + a*x + b*x**2 + c*x**3 + d*x**4
    # OeQ autogenerated correlation for 'Window to Wall Ratio in all Directions'
    Const= -37384.3262911
    a=     76.6249992981
    b=     -0.0588592044322
    c=     2.00825771495e-05
    d=     -2.56807721692e-09
    A_WIN_BY_AW = Const + a*x + b*x**2 + c*x**3 + d*x**4
 
    l_sum = A_WIN_E_BY_AW + A_WIN_S_BY_AW + A_WIN_W_BY_AW + A_WIN_N_BY_AW + A_WIN_BY_AW
    if mode is 'distribution':
        return {'A_WIN_E_BY_AW' : A_WIN_E_BY_AW/l_sum, 'A_WIN_S_BY_AW' : A_WIN_S_BY_AW/l_sum, 'A_WIN_W_BY_AW' : A_WIN_W_BY_AW/l_sum, 'A_WIN_N_BY_AW' : A_WIN_N_BY_AW/l_sum, 'A_WIN_BY_AW' : A_WIN_BY_AW/l_sum}

    return(A_WIN_E_BY_AW/l_sum * 1850 + A_WIN_S_BY_AW/l_sum * 1935 + A_WIN_W_BY_AW/l_sum * 1954.5 + A_WIN_N_BY_AW/l_sum * 1964.5 + A_WIN_BY_AW/l_sum * 1974.5 )


