# OeQ autogenerated correlation for 'Flat Size in Correlation to population density '

import math
import numpy as np
import oeqCorrelation as oeq
def get(*xin):

    # OeQ autogenerated correlation for 'Total Living Area of all Flats of a Building'
    TOTAL_LIVING_AREA= oeq.correlation(
    const= 43.7253855167,
    a=     86.8012814518,
    b=     -21.0749436912,
    c=     1.74298203253,
    mode= "log")

    return dict(TOTAL_LIVING_AREA=TOTAL_LIVING_AREA.lookup(*xin))

