# OeQ autogenerated correlation for 'Living Area in a Building in Correlation to the Portion of 1-Flat-Buildings'

import math
import numpy as np
import oeqCorrelation as oeq
def get(*xin):

    # OeQ autogenerated correlation for 'Total Living Area of all Flats of a Building'
    TOTAL_LIVING_AREA= oeq.correlation(
    const= -28471.1072776,
    a=     28134.0622125,
    b=     -10211.7606319,
    c=     1632.64934766,
    d=     -97.4884321219,
    mode= "log")

    return dict(TOTAL_LIVING_AREA=TOTAL_LIVING_AREA.lookup(*xin))

