# OeQ autogenerated correlation for 'Flat Size in Correlation to the Number of Flats'

import math
import numpy as np
import oeqCorrelation as oeq
def get(*xin):

    # OeQ autogenerated correlation for 'Average Living Area per Flat'
    FLT_AREA_AVG= oeq.correlation(
    const= 122.980287092,
    a=     -44.2471227557,
    b=     5.36442245814,
    c=     0.0733369635774,
    mode= "log")

    return dict(FLT_AREA_AVG=FLT_AREA_AVG.lookup(*xin))

print get(100)
