# OeQ autogenerated correlation for 'Flat Size in Correlation to population density '

import math
import numpy as np
import oeqCorrelation as oeq
def get(*xin):

    # OeQ autogenerated correlation for 'Average Living Area per Flat'
    FLT_AREA_AVG= oeq.correlation(
    const= 75.3919257424,
    a=      29.666684108,
    b=     -5.80383559945,
    c=     0.274490902828,
    mode= "log")

    return dict(FLT_AREA_AVG=FLT_AREA_AVG.lookup(*xin))

