# OeQ autogenerated correlation for 'Flat Size in Correlation to the Number of Rooms'

import math
import numpy as np
import oeqCorrelation as oeq
def get(*xin):

    # OeQ autogenerated correlation for 'Average Living Area per Flat'
    FLT_AREA_AVG= oeq.correlation(
    const= 118.872386642,
    a=     -13.3481881263,
    b=     -41.9531736183,
    c=     19.1934704812,
    mode= "log")

    return dict(FLT_AREA_AVG=FLT_AREA_AVG.lookup(*xin))

