# OeQ autogenerated correlation for 'Living Area in a Building in Correlation to the Portion of Buildings with more than 13 Flats'

import math
import numpy as np
import oeqCorrelation as oeq
def get(*xin):

    # OeQ autogenerated correlation for 'Total Living Area of all Flats of a Building'
    TOTAL_LIVING_AREA= oeq.correlation(
    const= 188.523858782,
    a=     17.3494332989,
    b=     -0.107423406217,
    c=     0.000350912932676,
    mode= "lin")

    return dict(TOTAL_LIVING_AREA=TOTAL_LIVING_AREA.lookup(*xin))

