# OeQ autogenerated correlation function: Flat Size in Correlation to population density 

building_living_area_by_population_density_corr<-function(...){
# OeQ autogenerated correlation for 'Total Living Area of all Flats of a Building'
TOTAL_LIVING_AREA = correlation(
    Const = 43.7253855167437,
    a = 86.8012814518147,
    b = -21.0749436911529,
    c = 1.74298203253123,
    mode="log")


    return(data.frame(TOTAL_LIVING_AREA=lookup(TOTAL_LIVING_AREA,...),
    stringsAsFactors=FALSE))
}
