# OeQ autogenerated correlation function: Building Heating Type Distribution in Correlation to the population density

building_heating_type_distribution_by_population_density_correlation<-function(...){
# OeQ autogenerated correlation for 'Buildings with housing heated by district heating systems'
BLD_HEAT_DISTR = correlation(
    Const = -0.0497312239063417,
    a = 0.0751958286351235,
    b = -0.0283949974780115,
    c = 0.00423665454622439,
    d = -0.000197740004602775,
    mode="log")

# OeQ autogenerated correlation for 'Buildings with housing heated by self-contained central heating systems'
BLD_HEAT_SCDWELL = correlation(
    Const = -0.0645092636623148,
    a = 0.0926296333827822,
    b = -0.0320120926991971,
    c = 0.00440158167660176,
    d = -0.000189576081619269,
    mode="log")

# OeQ autogenerated correlation for 'Buildings with housing heated by block-type combined heat and power plants'
BLD_HEAT_BLOCKTYPE = correlation(
    Const = -0.00464954316969173,
    a = 0.0109703900192651,
    b = -0.00348569366697665,
    c = 0.00040012758011574,
    d = -1.15620456969315e-05,
    mode="log")

# OeQ autogenerated correlation for 'Buildings with housing heated by '
BLD_HEAT_CENTRAL = correlation(
    Const = 1.39552942758993,
    a = -0.682865258739624,
    b = 0.244048940170247,
    c = -0.0338635816391628,
    d = 0.00159286982263754,
    mode="log")

# OeQ autogenerated correlation for 'Buildings with housing heated by single room heating systems including stoves and night storage heaters'
BLD_HEAT_SNGLROOM = correlation(
    Const = 0.0827660836629009,
    a = 0.0966309375396238,
    b = -0.035724488185145,
    c = 0.00432678548533928,
    d = -0.000180797989533513,
    mode="log")

# OeQ autogenerated correlation for 'Buildings w/ housing without heating systems'
BLD_HEAT_NONE = correlation(
    Const = -0.0276354062692015,
    a = 0.0426818409653616,
    b = -0.0141287580666734,
    c = 0.00180784004959506,
    d = -8.11193054338878e-05,
    mode="log")


    return(data.frame(BLD_HEAT_DISTR=lookup(BLD_HEAT_DISTR,...),
    BLD_HEAT_SCDWELL=lookup(BLD_HEAT_SCDWELL,...),
    BLD_HEAT_BLOCKTYPE=lookup(BLD_HEAT_BLOCKTYPE,...),
    BLD_HEAT_CENTRAL=lookup(BLD_HEAT_CENTRAL,...),
    BLD_HEAT_SNGLROOM=lookup(BLD_HEAT_SNGLROOM,...),
    BLD_HEAT_NONE=lookup(BLD_HEAT_NONE,...),
    stringsAsFactors=FALSE))
}
