# OeQ autogenerated correlation function: Living Area in a Building in Correlation to the Portion of 2-Flat-Buildings

building_living_area_by_portion_of_2_flat_buildings_corr<-function(...){
# OeQ autogenerated correlation for 'Total Living Area of all Flats of a Building'
TOTAL_LIVING_AREA = correlation(
    Const = 139.56702021356,
    a = 440.928668011791,
    b = -1536.7449089065,
    c = 1613.73238622136,
    mode="lin")


    return(data.frame(TOTAL_LIVING_AREA=lookup(TOTAL_LIVING_AREA,...),
    stringsAsFactors=FALSE))
}
