# OeQ autogenerated correlation function: Building Owner Distribution in Correlation to the population density

building_owner_distribution_by_population_density_correlation<-function(...){
# OeQ autogenerated correlation for 'Buildings with housing owned by assiciations'
BLD_OWNER_ASSOC = correlation(
    Const = 0.0312402617762993,
    a = 0.0118744160583817,
    b = -0.00729746079841898,
    c = 0.00173208156048849,
    d = -9.53526866705913e-05,
    mode="log")

# OeQ autogenerated correlation for 'Buildings with housing owned by private persons'
BLD_OWNER_PRIV = correlation(
    Const = 0.870142013651714,
    a = 0.012590214391935,
    b = 0.0042357528484209,
    c = -0.00101572305977848,
    mode="log")

# OeQ autogenerated correlation for ''
BLD_OWNER_BUILDSOC = correlation(
    Const = 7.05505520926564e-05,
    a = 2.4140586889608e-05,
    b = -8.36861380786779e-09,
    c = 1.19731589642192e-12,
    d = -3.91117785943757e-17,
    mode="lin")

# OeQ autogenerated correlation for 'Buildings with housing owned by muicipalities and municipal housing companies'
BLD_OWNER_MUNDWELLCOMP = correlation(
    Const = 0.0119495453474963,
    a = 0.00711820124277206,
    b = -0.0030357909459752,
    c = 0.000296825110285547,
    mode="log")

# OeQ autogenerated correlation for 'Buildings with housing owned by private housing companies'
BLD_OWNER_PRIVDWELLCOMP = correlation(
    Const = -0.00352036390092346,
    a = 0.00501006910544007,
    b = -0.00043611603948085,
    c = -0.00030317276038083,
    d = 4.66056854617071e-05,
    mode="log")

# OeQ autogenerated correlation for 'Buildings with housing owned by other private companies'
BLD_OWNER_OTHERPRIVCOMP = correlation(
    Const = 5.20837989709892e-05,
    a = 0.00594480102355594,
    b = -0.00189094906311234,
    c = 0.000167059857311857,
    mode="log")

# OeQ autogenerated correlation for 'Buildings with housing owned by government'
BLD_OWNER_GOV = correlation(
    Const = 0.00125717232548518,
    a = 3.53179848583883e-06,
    b = -2.32282383087474e-09,
    c = 4.87405593612328e-13,
    mode="lin")

# OeQ autogenerated correlation for 'Buildings with housing owned by nongovernment organisations'
BLD_OWNER_ORG = correlation(
    Const = -0.00178904938759423,
    a = 0.00356828920261927,
    b = -0.000892835212844168,
    c = 7.13734965882492e-05,
    mode="log")


    return(data.frame(BLD_OWNER_ASSOC=lookup(BLD_OWNER_ASSOC,...),
    BLD_OWNER_PRIV=lookup(BLD_OWNER_PRIV,...),
    BLD_OWNER_BUILDSOC=lookup(BLD_OWNER_BUILDSOC,...),
    BLD_OWNER_MUNDWELLCOMP=lookup(BLD_OWNER_MUNDWELLCOMP,...),
    BLD_OWNER_PRIVDWELLCOMP=lookup(BLD_OWNER_PRIVDWELLCOMP,...),
    BLD_OWNER_OTHERPRIVCOMP=lookup(BLD_OWNER_OTHERPRIVCOMP,...),
    BLD_OWNER_GOV=lookup(BLD_OWNER_GOV,...),
    BLD_OWNER_ORG=lookup(BLD_OWNER_ORG,...),
    stringsAsFactors=FALSE))
}
