# OeQ autogenerated correlation function: Living Area in a Building in Correlation to the Portion of 1-Flat-Buildings

building_living_area_by_portion_of_1_flat_buildings_corr<-function(...){
# OeQ autogenerated correlation for 'Total Living Area of all Flats of a Building'
TOTAL_LIVING_AREA = correlation(
    Const = -28471.10727757,
    a = 28134.0622125322,
    b = -10211.7606318981,
    c = 1632.64934766172,
    d = -97.4884321218927,
    mode="log")


    return(data.frame(TOTAL_LIVING_AREA=lookup(TOTAL_LIVING_AREA,...),
    stringsAsFactors=FALSE))
}
