# OeQ autogenerated correlation function: Number of Common walls in Correlation to population density 

common_walls_by_population_density_corr<-function(...){
# OeQ autogenerated correlation for 'Average Number of Common Walls per Flat'
FLT_COMWALL_AVG = correlation(
    Const = 0.0844256206668605,
    a = 0.50934540741523,
    b = -0.224269236004749,
    c = 0.0342874642334565,
    d = -0.00146672896542952,
    mode="log")


    return(data.frame(FLT_COMWALL_AVG=lookup(FLT_COMWALL_AVG,...),
    stringsAsFactors=FALSE))
}
