# OeQ autogenerated correlation function: Buildings with n flats in correlation to population density

distribution_by_population_density<-function(...){
# OeQ autogenerated correlation for 'Buildings with housing with 1 flat'
BLD_NOFLAT_1 = correlation(
    Const = 1.07781959235196,
    a = -0.191560414505247,
    b = 0.0390092507965437,
    c = -0.00297387956952792,
    d = 1.07781959235196,
    mode="log")

# OeQ autogenerated correlation for 'Buildings with housing with 2 flats'
BLD_NOFLAT_2 = correlation(
    Const = -0.105048021491829,
    a = 0.172471300374424,
    b = -0.0385246868011514,
    c = 0.00427310573784063,
    d = -0.000213769103586585,
    mode="log")

# OeQ autogenerated correlation for 'Buildings with housing with 3 up to 6 flats'
BLD_NOFLAT_3TO6 = correlation(
    Const = 0.0401278689213071,
    a = 0.0101662719166317,
    b = -0.00362339425514449,
    c = 0.000599342447600934,
    d = 0.0401278689213071,
    mode="log")

# OeQ autogenerated correlation for 'Buildings with housing with 7 up to 12 flats'
BLD_NOFLAT_7TO12 = correlation(
    Const = 0.02264139884508,
    a = -0.0354053279533926,
    b = 0.0180122571390444,
    c = -0.00356706888547236,
    d = 0.000257056615638445,
    mode="log")

# OeQ autogenerated correlation for 'Buildings with housing with more than 13 flats'
BLD_NOFLAT_MTH13 = correlation(
    Const = 0.0219670735061898,
    a = -0.0328764453965002,
    b = 0.0162840430351832,
    c = -0.00314225243169467,
    d = 0.000207327056983923,
    mode="log")


    return(data.frame(BLD_NOFLAT_1=lookup(BLD_NOFLAT_1,...),
    BLD_NOFLAT_2=lookup(BLD_NOFLAT_2,...),
    BLD_NOFLAT_3TO6=lookup(BLD_NOFLAT_3TO6,...),
    BLD_NOFLAT_7TO12=lookup(BLD_NOFLAT_7TO12,...),
    BLD_NOFLAT_MTH13=lookup(BLD_NOFLAT_MTH13,...),
    stringsAsFactors=FALSE))
}
