# OeQ autogenerated correlation function: Flat Owner Distribution in Correlation to the population density

flat_owner_distribution_by_population_density_correlation<-function(...){
# OeQ autogenerated correlation for 'Flats owned by assiciations in buildings with housing'
FLT_OWNER_ASSOC = correlation(
    Const = 0.0382406726620737,
    a = 0.0536153782633843,
    b = -0.0351347180780179,
    c = 0.00829837639638804,
    d = -0.00052334363693983,
    mode="log")

# OeQ autogenerated correlation for 'Flats owned by private persons in buildings with housing'
FLT_OWNER_PRIV = correlation(
    Const = 0.769540217550818,
    a = 0.107717748880327,
    b = -0.0226050631116742,
    c = 0.000482584575234001,
    mode="log")

# OeQ autogenerated correlation for 'Flats owned by societies in buildings with housing'
FLT_OWNER_BUILDSOC = correlation(
    Const = 0.000497056078438511,
    a = 7.15504094488374e-05,
    b = -3.51267523097299e-08,
    c = 7.0897053651232e-12,
    d = -4.91258164829028e-16,
    mode="lin")

# OeQ autogenerated correlation for 'Flats owned by muicipalities and municipal housing companies in buildings with housing '
FLT_OWNER_MUNDWELLCOMP = correlation(
    Const = 0.0208587742518474,
    a = 2.36237985744048e-05,
    b = -1.14776836815315e-08,
    c = 2.09228384380647e-12,
    mode="lin")

# OeQ autogenerated correlation for 'Flats owned by private housing companies in buildings with housing'
FLT_OWNER_PRIVDWELLCOMP = correlation(
    Const = -0.0176152576183064,
    a = 0.024725803577335,
    b = -0.00839915003845142,
    c = 0.000874716026182999,
    mode="log")

# OeQ autogenerated correlation for 'Flats owned by other private companies in buildings with housing'
FLT_OWNER_OTHERPRIVCOMP = correlation(
    Const = -0.00793934343275028,
    a = 0.0146521855819907,
    b = -0.00414270576931665,
    c = 0.000350180363825937,
    mode="log")

# OeQ autogenerated correlation for 'Flats owned by government in buildings with housing'
FLT_OWNER_GOV = correlation(
    Const = -0.00228690737982868,
    a = 1.79619828145298e-05,
    b = -9.77923788906521e-09,
    c = 1.65709885571852e-12,
    mode="lin")

# OeQ autogenerated correlation for 'Flats owned by nongovernment organisations in buildings with housing'
FLT_OWNER_ORG = correlation(
    Const = 0.0125586007218053,
    a = -0.0182576725727281,
    b = 0.00813016941143511,
    c = -0.00134384709698189,
    d = 7.64337974803627e-05,
    mode="log")


    return(data.frame(FLT_OWNER_ASSOC=lookup(FLT_OWNER_ASSOC,...),
    FLT_OWNER_PRIV=lookup(FLT_OWNER_PRIV,...),
    FLT_OWNER_BUILDSOC=lookup(FLT_OWNER_BUILDSOC,...),
    FLT_OWNER_MUNDWELLCOMP=lookup(FLT_OWNER_MUNDWELLCOMP,...),
    FLT_OWNER_PRIVDWELLCOMP=lookup(FLT_OWNER_PRIVDWELLCOMP,...),
    FLT_OWNER_OTHERPRIVCOMP=lookup(FLT_OWNER_OTHERPRIVCOMP,...),
    FLT_OWNER_GOV=lookup(FLT_OWNER_GOV,...),
    FLT_OWNER_ORG=lookup(FLT_OWNER_ORG,...),
    stringsAsFactors=FALSE))
}
