# OeQ autogenerated correlation function: Flat Size in Correlation to the Number of Rooms

flat_size_by_room_numbers_corr<-function(...){
# OeQ autogenerated correlation for 'Average Living Area per Flat'
FLT_AREA_AVG = correlation(
    Const = 118.872386642188,
    a = -13.3481881263401,
    b = -41.9531736182998,
    c = 19.1934704812391,
    d = 118.872386642188,
    mode="log")


    return(data.frame(FLT_AREA_AVG=lookup(FLT_AREA_AVG,...),
    stringsAsFactors=FALSE))
}
