# OeQ autogenerated correlation function: Flat Size in Correlation to the Number of Flats

flat_size_by_number_of_flats_corr<-function(...){
# OeQ autogenerated correlation for 'Average Living Area per Flat'
FLT_AREA_AVG = correlation(
    Const = 122.980287091933,
    a = -44.2471227556525,
    b = 5.36442245814376,
    c = 0.0733369635773591,
    d = 122.980287091933,
    mode="log")


    return(data.frame(FLT_AREA_AVG=lookup(FLT_AREA_AVG,...),
    stringsAsFactors=FALSE))
}
