# OeQ autogenerated correlation function: Flat Area in Correlation to the Population Density

flat_area_by_population_density<-function(...){
# OeQ autogenerated correlation for 'Average Living Area per Flat'
FLT_AREA_AVG = correlation(
    Const = 75.3919257424358,
    a = 29.6666841079613,
    b = -5.80383559944688,
    c = 0.27449090282824,
    d = 75.3919257424358,
    mode="log")


    return(data.frame(FLT_AREA_AVG=lookup(FLT_AREA_AVG,...),
    stringsAsFactors=FALSE))
}
