# OeQ autogenerated correlation function: Living Area in a Building in Correlation to the Portion of Buildings with 3 to 6 Flats

living_area_by_portion_of_3to6_flat_buildings_corr<-function(...){
# OeQ autogenerated correlation for 'Total Living Area of all Flats of a Building'
TOTAL_LIVING_AREA = correlation(
    Const = 148.113118680072,
    a = 4.83420245803118,
    b = -0.0934802870571301,
    c = 0.00119008231226576,
    d = -4.54076922254185e-06,
    mode="lin")


    return(data.frame(TOTAL_LIVING_AREA=lookup(TOTAL_LIVING_AREA,...),
    stringsAsFactors=FALSE))
}
