# OeQ autogenerated correlation function: Living Area in a Building in Correlation to the Portion of Buildings with 3 to 6 Flats

living_area_by_portion_of_7to12_flat_buildings_corr<-function(...){
# OeQ autogenerated correlation for 'Total Living Area of all Flats of a Building'
TOTAL_LIVING_AREA = correlation(
    Const = 170.892227121481,
    a = 5.50987585060621,
    b = -0.000228398571372604,
    c = -0.000119754558791589,
    mode="lin")


    return(data.frame(TOTAL_LIVING_AREA=lookup(TOTAL_LIVING_AREA,...),
    stringsAsFactors=FALSE))
}
