# OeQ autogenerated correlation function: Living Area in a Building in Correlation to the Portion of Buildings with more than 13 Flats

living_area_by_portion_of_mth13_flat_buildings_corr<-function(...){
# OeQ autogenerated correlation for 'Total Living Area of all Flats of a Building'
TOTAL_LIVING_AREA = correlation(
    Const = 188.523858781908,
    a = 17.3494332988528,
    b = -0.107423406217236,
    c = 0.000350912932676285,
    mode="lin")


    return(data.frame(TOTAL_LIVING_AREA=lookup(TOTAL_LIVING_AREA,...),
    stringsAsFactors=FALSE))
}
