# OeQ autogenerated correlation function: Number of Flats per Building in Correlation to population density 

number_of_flats_by_population_density_corr<-function(...){
# OeQ autogenerated correlation for 'Average Number of Flats per Building'
BLD_NOFLAT_AVG = correlation(
    Const = 0.496063962509243,
    a = 0.832051782819032,
    b = -0.245727278911672,
    c = 0.0236730875559566,
    mode="log")


    return(data.frame(BLD_NOFLAT_AVG=lookup(BLD_NOFLAT_AVG,...),
    stringsAsFactors=FALSE))
}
