# OeQ autogenerated correlation function: Flat Size in Correlation to population density 

total_living_area_by_building_density_corr<-function(...){
# OeQ autogenerated correlation for 'NULL'
TOTAL_LIVING_AREA = correlation(
    Const = 16.9612111140651,
    a = 37.3699270344133,
    b = -25.066880729002,
    c = 6.04869046956373,
    d = -0.472322343882074,
    mode="log")


    return(data.frame(TOTAL_LIVING_AREA=lookup(TOTAL_LIVING_AREA,...),
    stringsAsFactors=FALSE))
}
