# OeQ autogenerated correlation function: Window/Wall Ratio North in Correlation to the Building Age

window_wall_ratio_north_SDH_by_building_age_correlation<-function(...){
# OeQ autogenerated correlation for 'Window to Wall Ratio in Northern Direction'
A_WIN_N_BY_AW = correlation(
    Const = 13935.4897428795,
    a = -28.9315780487384,
    b = 0.0225109615696397,
    c = -7.77964739497752e-06,
    d = 1.00756447248457e-09,
    mode="lin")


    return(data.frame(A_WIN_N_BY_AW=lookup(A_WIN_N_BY_AW,...),
    stringsAsFactors=FALSE))
}
