# OeQ autogenerated correlation function: Window/Wall Ratio South in Correlation to the Building Age

window_wall_ratio_south_LMFH_by_building_age_correlation<-function(...){
# OeQ autogenerated correlation for 'Window to Wall Ratio in Southern Direction'
A_WIN_S_BY_AW = correlation(
    Const = -13703.8617286659,
    a = 28.4461323872265,
    b = -0.0221292947949616,
    c = 7.64632028070384e-06,
    d = -9.90104359077743e-10,
    mode="lin")


    return(data.frame(A_WIN_S_BY_AW=lookup(A_WIN_S_BY_AW,...),
    stringsAsFactors=FALSE))
}
