# OeQ autogenerated correlation function: Window/Wall Ratio in Correlation to the Building Age

window_wall_ratio_MFH_by_building_age_correlation<-function(...){
# OeQ autogenerated correlation for 'Window to Wall Ratio in all Directions'
A_WIN_BY_AW = correlation(
    Const = -38790.5022018085,
    a = 79.0503866068902,
    b = -0.0603881990871377,
    c = 2.04958423547438e-05,
    d = -2.6077500181529e-09,
    mode="lin")


    return(data.frame(A_WIN_BY_AW=lookup(A_WIN_BY_AW,...),
    stringsAsFactors=FALSE))
}
