# OeQ autogenerated correlation function: Window/Wall Ratio South in Correlation to the Building Age

window_wall_ratio_south_SDH_by_building_age_correlation<-function(...){
# OeQ autogenerated correlation for 'Window to Wall Ratio in Southern Direction'
A_WIN_S_BY_AW = correlation(
    Const = 21767.2741466309,
    a = -44.9572395176811,
    b = 0.0348009695481469,
    c = -1.19664134675611e-05,
    d = 1.54217258147093e-09,
    mode="lin")


    return(data.frame(A_WIN_S_BY_AW=lookup(A_WIN_S_BY_AW,...),
    stringsAsFactors=FALSE))
}
