# OeQ autogenerated correlation function: Window/Wall Ratio West in Correlation to the Building Age

window_wall_ratio_west_SFH_by_building_age_correlation<-function(...){
# OeQ autogenerated correlation for 'Window to Wall Ratio in Western Direction'
A_WIN_W_BY_AW = correlation(
    Const = 3443.04500822349,
    a = -7.03961089554205,
    b = 0.00539428257240699,
    c = -1.83599645650506e-06,
    d = 2.34190543055015e-10,
    mode="lin")


    return(data.frame(A_WIN_W_BY_AW=lookup(A_WIN_W_BY_AW,...),
    stringsAsFactors=FALSE))
}
