# OeQ autogenerated correlation function: Window/Wall Ratio in Correlation to the Building Age

window_wall_ratio_SDH_by_building_age_correlation<-function(...){
# OeQ autogenerated correlation for 'Window to Wall Ratio in all Directions'
A_WIN_BY_AW = correlation(
    Const = 23214.7776635173,
    a = -47.3526648501484,
    b = 0.0361917067716243,
    c = -1.22840089010866e-05,
    d = 1.56225770296391e-09,
    mode="lin")


    return(data.frame(A_WIN_BY_AW=lookup(A_WIN_BY_AW,...),
    stringsAsFactors=FALSE))
}
