# OeQ autogenerated correlation function: Window/Wall Ratio in Correlation to the Building Age

window_wall_ratio_AVG_by_building_age_correlation<-function(...){
# OeQ autogenerated correlation for 'Window to Wall Ratio in all Directions'
A_WIN_BY_AW = correlation(
    Const = -5481.11187181221,
    a = 11.1935821089001,
    b = -0.00857180719326586,
    c = 2.91747034600045e-06,
    d = -3.72396722857901e-10,
    mode="lin")


    return(data.frame(A_WIN_BY_AW=lookup(A_WIN_BY_AW,...),
    stringsAsFactors=FALSE))
}
