# OeQ autogenerated correlation function: Window/Wall Ratio West in Correlation to the Building Age

window_wall_ratio_west_MFH_by_building_age_correlation<-function(...){
# OeQ autogenerated correlation for 'Window to Wall Ratio in Western Direction'
A_WIN_W_BY_AW = correlation(
    Const = -37846.9118589637,
    a = 77.3456608212017,
    b = -0.0592490161432107,
    c = 2.0163120734111e-05,
    d = -2.57207834472878e-09,
    mode="lin")


    return(data.frame(A_WIN_W_BY_AW=lookup(A_WIN_W_BY_AW,...),
    stringsAsFactors=FALSE))
}
