# OeQ autogenerated correlation function: Window/Wall Ratio West in Correlation to the Building Age

window_wall_ratio_west_SDH_by_building_age_correlation<-function(...){
# OeQ autogenerated correlation for 'Window to Wall Ratio in Western Direction'
A_WIN_W_BY_AW = correlation(
    Const = -6820.10365041167,
    a = 14.441462185382,
    b = -0.0114555878046011,
    c = 4.03451500345243e-06,
    d = -5.32281636262988e-10,
    mode="lin")


    return(data.frame(A_WIN_W_BY_AW=lookup(A_WIN_W_BY_AW,...),
    stringsAsFactors=FALSE))
}
