# OeQ autogenerated correlation function: Window/Wall Ratio North in Correlation to the Building Age

window_wall_ratio_north_MFH_by_building_age_correlation<-function(...){
# OeQ autogenerated correlation for 'Window to Wall Ratio in Northern Direction'
A_WIN_N_BY_AW = correlation(
    Const = 14743.6179718705,
    a = -30.2572633912668,
    b = 0.0232730617400146,
    c = -7.95175130126522e-06,
    d = 1.01829432636616e-09,
    mode="lin")


    return(data.frame(A_WIN_N_BY_AW=lookup(A_WIN_N_BY_AW,...),
    stringsAsFactors=FALSE))
}
