# OeQ autogenerated correlation function: Window/Wall Ratio East in Correlation to the Building Age

window_wall_ratio_east_AVG_by_building_age_correlation<-function(...){
# OeQ autogenerated correlation for 'Window to Wall Ratio in Eastern Direction'
A_WIN_E_BY_AW = correlation(
    Const = -11117.2066108493,
    a = 22.7674576066136,
    b = -0.0174778241167759,
    c = 5.96090295140152e-06,
    d = -7.62099304536358e-10,
    mode="lin")


    return(data.frame(A_WIN_E_BY_AW=lookup(A_WIN_E_BY_AW,...),
    stringsAsFactors=FALSE))
}
