# OeQ autogenerated correlation function: Window/Wall Ratio North in Correlation to the Building Age

window_wall_ratio_north_AVG_by_building_age_correlation<-function(...){
# OeQ autogenerated correlation for 'Window to Wall Ratio in Northern Direction'
A_WIN_N_BY_AW = correlation(
    Const = 6691.72173786105,
    a = -13.7495989619803,
    b = 0.0105886901282848,
    c = -3.62224765125004e-06,
    d = 4.6442140913852e-10,
    mode="lin")


    return(data.frame(A_WIN_N_BY_AW=lookup(A_WIN_N_BY_AW,...),
    stringsAsFactors=FALSE))
}
