# OeQ autogenerated correlation function: Window/Wall Ratio South in Correlation to the Building Age

window_wall_ratio_south_AVG_by_building_age_correlation<-function(...){
# OeQ autogenerated correlation for 'Window to Wall Ratio in Southern Direction'
A_WIN_S_BY_AW = correlation(
    Const = 10168.4679084653,
    a = -20.8133662361341,
    b = 0.0159674047391129,
    c = -5.44156257373411e-06,
    d = 6.9507788152769e-10,
    mode="lin")


    return(data.frame(A_WIN_S_BY_AW=lookup(A_WIN_S_BY_AW,...),
    stringsAsFactors=FALSE))
}
