# OeQ autogenerated correlation function: Window/Wall Ratio in Correlation to the Building Age

window_wall_ratio_LMFH_by_building_age_correlation<-function(...){
# OeQ autogenerated correlation for 'Window to Wall Ratio in all Directions'
A_WIN_BY_AW = correlation(
    Const = -38227.0536346547,
    a = 78.3748866103524,
    b = -0.0602208889846028,
    c = 2.05531996790016e-05,
    d = -2.62903276952081e-09,
    mode="lin")


    return(data.frame(A_WIN_BY_AW=lookup(A_WIN_BY_AW,...),
    stringsAsFactors=FALSE))
}
