# OeQ autogenerated correlation function: Window/Wall Ratio in Correlation to the Building Age

window_wall_ratio_SFH_by_building_age_correlation<-function(...){
# OeQ autogenerated correlation for 'Window to Wall Ratio in all Directions'
A_WIN_BY_AW = correlation(
    Const = 31395.5662123127,
    a = -64.2747328811433,
    b = 0.0493180059638024,
    c = -1.68093075787265e-05,
    d = 2.1472820754456e-09,
    mode="lin")


    return(data.frame(A_WIN_BY_AW=lookup(A_WIN_BY_AW,...),
    stringsAsFactors=FALSE))
}
