# OeQ autogenerated correlation function: Window/Wall Ratio North in Correlation to the Building Age

window_wall_ratio_north_LMFH_by_building_age_correlation<-function(...){
# OeQ autogenerated correlation for 'Window to Wall Ratio in Northern Direction'
A_WIN_N_BY_AW = correlation(
    Const = -16855.7432878222,
    a = 34.8833074262759,
    b = -0.0270561638720356,
    c = 9.32124051087664e-06,
    d = -1.20350325915348e-09,
    mode="lin")


    return(data.frame(A_WIN_N_BY_AW=lookup(A_WIN_N_BY_AW,...),
    stringsAsFactors=FALSE))
}
