# OeQ autogenerated correlation function: Window/Wall Ratio West in Correlation to the Building Age

window_wall_ratio_west_LMFH_by_building_age_correlation<-function(...){
# OeQ autogenerated correlation for 'Window to Wall Ratio in Western Direction'
A_WIN_W_BY_AW = correlation(
    Const = -4590.02660381737,
    a = 9.07172432591048,
    b = -0.00670666922272456,
    c = 2.19817135124243e-06,
    d = -2.69506230435497e-10,
    mode="lin")


    return(data.frame(A_WIN_W_BY_AW=lookup(A_WIN_W_BY_AW,...),
    stringsAsFactors=FALSE))
}
