# OeQ autogenerated correlation function: Window/Wall Ratio West in Correlation to the Building Age

window_wall_west_ratio_AVG_by_building_age_correlation<-function(...){
# OeQ autogenerated correlation for 'Window to Wall Ratio in Western Direction'
A_WIN_W_BY_AW = correlation(
    Const = -11011.4956176899,
    a = 22.5506266092316,
    b = -0.0173111704287292,
    c = 5.90402069529199e-06,
    d = -7.54824690804281e-10,
    mode="lin")


    return(data.frame(A_WIN_W_BY_AW=lookup(A_WIN_W_BY_AW,...),
    stringsAsFactors=FALSE))
}
