# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_project_settings_form.ui'
#
# Created: Fri Sep 11 10:44:56 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_project_settings_form(object):
    def setupUi(self, project_settings_form):
        project_settings_form.setObjectName(_fromUtf8("project_settings_form"))
        project_settings_form.resize(483, 534)
        project_settings_form.setStyleSheet(_fromUtf8("#form QLineEdit {\n"
"    color: rgb(151, 151, 151,95);\n"
"}\n"
"\n"
"#form QLineEdit:focus {\n"
"    color: rgb(0,0,0);\n"
"}"))
        self.verticalLayout = QtGui.QVBoxLayout(project_settings_form)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.form = QtGui.QFrame(project_settings_form)
        self.form.setFocusPolicy(QtCore.Qt.NoFocus)
        self.form.setStyleSheet(_fromUtf8(""))
        self.form.setFrameShape(QtGui.QFrame.StyledPanel)
        self.form.setFrameShadow(QtGui.QFrame.Raised)
        self.form.setObjectName(_fromUtf8("form"))
        self.gridLayout = QtGui.QGridLayout(self.form)
        self.gridLayout.setHorizontalSpacing(15)
        self.gridLayout.setVerticalSpacing(6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.climate_zone_layout = QtGui.QHBoxLayout()
        self.climate_zone_layout.setSpacing(0)
        self.climate_zone_layout.setObjectName(_fromUtf8("climate_zone_layout"))
        self.gridLayout.addLayout(self.climate_zone_layout, 5, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gridLayout.addLayout(self.horizontalLayout, 12, 0, 1, 1)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.project_name = QtGui.QLineEdit(self.form)
        self.project_name.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.project_name.setText(_fromUtf8(""))
        self.project_name.setObjectName(_fromUtf8("project_name"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.project_name)
        self.location_label_11 = QtGui.QLabel(self.form)
        self.location_label_11.setObjectName(_fromUtf8("location_label_11"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.location_label_11)
        self.location_layout = QtGui.QHBoxLayout()
        self.location_layout.setObjectName(_fromUtf8("location_layout"))
        self.location_city = QtGui.QLineEdit(self.form)
        self.location_city.setMinimumSize(QtCore.QSize(228, 0))
        self.location_city.setText(_fromUtf8(""))
        self.location_city.setObjectName(_fromUtf8("location_city"))
        self.location_layout.addWidget(self.location_city)
        self.lookup_by_address = QtGui.QPushButton(self.form)
        self.lookup_by_address.setMinimumSize(QtCore.QSize(25, 21))
        self.lookup_by_address.setMaximumSize(QtCore.QSize(25, 21))
        self.lookup_by_address.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/Controls/icons/magnifying_glass.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.lookup_by_address.setIcon(icon)
        self.lookup_by_address.setFlat(True)
        self.lookup_by_address.setObjectName(_fromUtf8("lookup_by_address"))
        self.location_layout.addWidget(self.lookup_by_address)
        self.formLayout_2.setLayout(3, QtGui.QFormLayout.FieldRole, self.location_layout)
        self.zip_label = QtGui.QLabel(self.form)
        self.zip_label.setObjectName(_fromUtf8("zip_label"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.zip_label)
        self.location_postal = QtGui.QLineEdit(self.form)
        self.location_postal.setMaximumSize(QtCore.QSize(800, 21))
        self.location_postal.setText(_fromUtf8(""))
        self.location_postal.setObjectName(_fromUtf8("location_postal"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.location_postal)
        self.longitude_label = QtGui.QLabel(self.form)
        self.longitude_label.setObjectName(_fromUtf8("longitude_label"))
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.LabelRole, self.longitude_label)
        self.location_layout_2 = QtGui.QHBoxLayout()
        self.location_layout_2.setObjectName(_fromUtf8("location_layout_2"))
        self.location_lon = QtGui.QLineEdit(self.form)
        self.location_lon.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.location_lon.setText(_fromUtf8(""))
        self.location_lon.setPlaceholderText(_fromUtf8("Longitude"))
        self.location_lon.setObjectName(_fromUtf8("location_lon"))
        self.location_layout_2.addWidget(self.location_lon)
        self.lookup_by_coords = QtGui.QPushButton(self.form)
        self.lookup_by_coords.setMinimumSize(QtCore.QSize(25, 21))
        self.lookup_by_coords.setMaximumSize(QtCore.QSize(25, 21))
        self.lookup_by_coords.setText(_fromUtf8(""))
        self.lookup_by_coords.setIcon(icon)
        self.lookup_by_coords.setFlat(True)
        self.lookup_by_coords.setObjectName(_fromUtf8("lookup_by_coords"))
        self.location_layout_2.addWidget(self.lookup_by_coords)
        self.formLayout_2.setLayout(6, QtGui.QFormLayout.FieldRole, self.location_layout_2)
        self.lattitude_label = QtGui.QLabel(self.form)
        self.lattitude_label.setObjectName(_fromUtf8("lattitude_label"))
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.LabelRole, self.lattitude_label)
        self.location_lat = QtGui.QLineEdit(self.form)
        self.location_lat.setMinimumSize(QtCore.QSize(323, 21))
        self.location_lat.setMaximumSize(QtCore.QSize(800, 21))
        self.location_lat.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.location_lat.setText(_fromUtf8(""))
        self.location_lat.setObjectName(_fromUtf8("location_lat"))
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.FieldRole, self.location_lat)
        self.crs_label = QtGui.QLabel(self.form)
        self.crs_label.setObjectName(_fromUtf8("crs_label"))
        self.formLayout_2.setWidget(8, QtGui.QFormLayout.LabelRole, self.crs_label)
        self.location_crs = QtGui.QLineEdit(self.form)
        self.location_crs.setMaximumSize(QtCore.QSize(800, 21))
        self.location_crs.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.location_crs.setText(_fromUtf8(""))
        self.location_crs.setObjectName(_fromUtf8("location_crs"))
        self.formLayout_2.setWidget(8, QtGui.QFormLayout.FieldRole, self.location_crs)
        self.heating_degree_days_label = QtGui.QLabel(self.form)
        self.heating_degree_days_label.setToolTip(_fromUtf8(""))
        self.heating_degree_days_label.setObjectName(_fromUtf8("heating_degree_days_label"))
        self.formLayout_2.setWidget(10, QtGui.QFormLayout.LabelRole, self.heating_degree_days_label)
        self.heating_degree_days = QtGui.QLineEdit(self.form)
        self.heating_degree_days.setMaximumSize(QtCore.QSize(800, 16777215))
        self.heating_degree_days.setObjectName(_fromUtf8("heating_degree_days"))
        self.formLayout_2.setWidget(10, QtGui.QFormLayout.FieldRole, self.heating_degree_days)
        self.average_build_year_label = QtGui.QLabel(self.form)
        self.average_build_year_label.setObjectName(_fromUtf8("average_build_year_label"))
        self.formLayout_2.setWidget(11, QtGui.QFormLayout.LabelRole, self.average_build_year_label)
        self.average_build_year = QtGui.QLineEdit(self.form)
        self.average_build_year.setMaximumSize(QtCore.QSize(800, 16777215))
        self.average_build_year.setObjectName(_fromUtf8("average_build_year"))
        self.formLayout_2.setWidget(11, QtGui.QFormLayout.FieldRole, self.average_build_year)
        self.population_density_label = QtGui.QLabel(self.form)
        self.population_density_label.setObjectName(_fromUtf8("population_density_label"))
        self.formLayout_2.setWidget(12, QtGui.QFormLayout.LabelRole, self.population_density_label)
        self.population_density = QtGui.QLineEdit(self.form)
        self.population_density.setMaximumSize(QtCore.QSize(800, 16777215))
        self.population_density.setObjectName(_fromUtf8("population_density"))
        self.formLayout_2.setWidget(12, QtGui.QFormLayout.FieldRole, self.population_density)
        self.description = QtGui.QPlainTextEdit(self.form)
        self.description.setObjectName(_fromUtf8("description"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.description)
        self.project_name_label = QtGui.QLabel(self.form)
        self.project_name_label.setObjectName(_fromUtf8("project_name_label"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.project_name_label)
        self.description_label = QtGui.QLabel(self.form)
        self.description_label.setObjectName(_fromUtf8("description_label"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.description_label)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout_2.setItem(2, QtGui.QFormLayout.FieldRole, spacerItem)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout_2.setItem(5, QtGui.QFormLayout.LabelRole, spacerItem1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout_2.setItem(5, QtGui.QFormLayout.FieldRole, spacerItem2)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout_2.setItem(9, QtGui.QFormLayout.FieldRole, spacerItem3)
        self.gridLayout.addLayout(self.formLayout_2, 0, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(self.form)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel | QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 17, 0, 1, 1)
        self.verticalLayout.addWidget(self.form)

        self.retranslateUi(project_settings_form)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), project_settings_form.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), project_settings_form.reject)
        QtCore.QMetaObject.connectSlotsByName(project_settings_form)
        project_settings_form.setTabOrder(self.project_name, self.location_city)
        project_settings_form.setTabOrder(self.location_city, self.location_postal)
        project_settings_form.setTabOrder(self.location_postal, self.heating_degree_days)
        project_settings_form.setTabOrder(self.heating_degree_days, self.average_build_year)
        project_settings_form.setTabOrder(self.average_build_year, self.population_density)
        project_settings_form.setTabOrder(self.population_density, self.location_lat)
        project_settings_form.setTabOrder(self.location_lat, self.buttonBox)
        project_settings_form.setTabOrder(self.buttonBox, self.lookup_by_address)
        project_settings_form.setTabOrder(self.lookup_by_address, self.lookup_by_coords)
        project_settings_form.setTabOrder(self.lookup_by_coords, self.location_crs)
        project_settings_form.setTabOrder(self.location_crs, self.location_lon)

    def retranslateUi(self, project_settings_form):
        project_settings_form.setWindowTitle(_translate("project_settings_form", "Dialog", None))
        self.project_name.setToolTip(_translate("project_settings_form", "Name of the project", None))
        self.project_name.setPlaceholderText(_translate("project_settings_form", "MyProject", None))
        self.location_label_11.setText(_translate("project_settings_form", "Location:", None))
        self.location_city.setPlaceholderText(_translate("project_settings_form", "City, Street", None))
        self.lookup_by_address.setToolTip(_translate("project_settings_form", "Lookup address", None))
        self.zip_label.setText(_translate("project_settings_form", "ZIP:", None))
        self.location_postal.setPlaceholderText(_translate("project_settings_form", "Postal Code", None))
        self.longitude_label.setText(_translate("project_settings_form", "Longitude", None))
        self.lookup_by_coords.setToolTip(_translate("project_settings_form", "Lookup coordinates", None))
        self.lattitude_label.setText(_translate("project_settings_form", "Lattitude", None))
        self.location_lat.setPlaceholderText(_translate("project_settings_form", "Latitude", None))
        self.crs_label.setText(_translate("project_settings_form", "CRS", None))
        self.location_crs.setPlaceholderText(_translate("project_settings_form", "CRS", None))
        self.heating_degree_days_label.setText(_translate("project_settings_form", "HeatDegDays:", None))
        self.heating_degree_days.setText(_translate("project_settings_form", "390.06", None))
        self.average_build_year_label.setToolTip(_translate("project_settings_form", "Average year of construction on the building stock", None))
        self.average_build_year_label.setText(_translate("project_settings_form", "Year of Constr", None))
        self.average_build_year.setText(_translate("project_settings_form", "1917", None))
        self.population_density_label.setToolTip(_translate("project_settings_form", "Population density of the investigation area (inhabitants per square kilometre)", None))
        self.population_density_label.setText(_translate("project_settings_form", "PopDensity:", None))
        self.population_density.setText(_translate("project_settings_form", "3.859", None))
        self.project_name_label.setToolTip(_translate("project_settings_form", "Name of the project", None))
        self.project_name_label.setText(_translate("project_settings_form", "Project Name:", None))
        self.description_label.setToolTip(_translate("project_settings_form", "Short description of the project", None))
        self.description_label.setText(_translate("project_settings_form", "Description:", None))

import resources_rc
