# OeQ autogenerated correlation for 'Age distribution in correlation to average year of construction'

import math
import numpy as np
from . import oeqCorrelation as oeq
def age_distribution_by_average_year_of_construction(*xin):

    # OeQ autogenerated correlation for 'NULL'
    BLD_AGE1_BEFORE1919= oeq.correlation(
    const= 17305.6055113,
    a=     -36.3881499767,
    b=     0.0287164086005,
    c=     -1.00779128691e-05,
    d=     1.32677126018e-09,
    mode= "lin")
    # OeQ autogenerated correlation for 'NULL'
    BLD_AGE1_1919TO1949= oeq.correlation(
    const= 35569.8677831,
    a=     -74.5130920293,
    b=     0.0584852319919,
    c=     -2.03850586481e-05,
    d=     2.66224063943e-09,
    mode= "lin")
    # OeQ autogenerated correlation for 'NULL'
    BLD_AGE1_1950TO1959= oeq.correlation(
    const=  19634.851143,
    a=     -40.3139110208,
    b=     0.0310158404272,
    c=     -1.0597324233e-05,
    d=     1.35676404023e-09,
    mode= "lin")
    # OeQ autogenerated correlation for 'NULL'
    BLD_AGE1_1960TO1969= oeq.correlation(
    const= 1565.83829057,
    a=     -2.45714853733,
    b=     0.00128442363581,
    c=     -2.2364578333e-07,
    mode= "lin")
    # OeQ autogenerated correlation for 'NULL'
    BLD_AGE1_1970TO1979= oeq.correlation(
    const= -13807.4794397,
    a=     29.4456917826,
    b=     -0.0235344705472,
    c=     8.3548190733e-06,
    d=     -1.11152868813e-09,
    mode= "lin")
    # OeQ autogenerated correlation for 'NULL'
    BLD_AGE1_1980TO1989= oeq.correlation(
    const= -30975.4127214,
    a=     64.4257617573,
    b=     -0.0502414455583,
    c=     1.74102147726e-05,
    d=     -2.26199334127e-09,
    mode= "lin")
    # OeQ autogenerated correlation for 'NULL'
    BLD_AGE1_1990TO1999= oeq.correlation(
    const= -78927.6111133,
    a=     163.688015644,
    b=     -0.127255654658,
    c=     4.39532475707e-05,
    d=     -5.69071518752e-09,
    mode= "lin")
    # OeQ autogenerated correlation for 'NULL'
    BLD_AGE1_2000TO2005= oeq.correlation(
    const= 11766.6009045,
    a=     -24.6792191619,
    b=     0.0194109659543,
    c=     -6.78574716302e-06,
    d=     8.89633599806e-10,
    mode= "lin")
    # OeQ autogenerated correlation for 'NULL'
    BLD_AGE1_AFTER2006= oeq.correlation(
    const= 44628.2541018,
    a=     -93.1984482031,
    b=     0.0729744813998,
    c=     -2.53912946008e-05,
    d=     3.31257598651e-09,
    mode= "lin")

    return dict(BLD_AGE1_BEFORE1919=BLD_AGE1_BEFORE1919.lookup(*xin),
    BLD_AGE1_1919TO1949=BLD_AGE1_1919TO1949.lookup(*xin),
    BLD_AGE1_1950TO1959=BLD_AGE1_1950TO1959.lookup(*xin),
    BLD_AGE1_1960TO1969=BLD_AGE1_1960TO1969.lookup(*xin),
    BLD_AGE1_1970TO1979=BLD_AGE1_1970TO1979.lookup(*xin),
    BLD_AGE1_1980TO1989=BLD_AGE1_1980TO1989.lookup(*xin),
    BLD_AGE1_1990TO1999=BLD_AGE1_1990TO1999.lookup(*xin),
    BLD_AGE1_2000TO2005=BLD_AGE1_2000TO2005.lookup(*xin),
    BLD_AGE1_AFTER2006=BLD_AGE1_AFTER2006.lookup(*xin))

