# OeQ autogenerated correlation for 'Flat Size in Correlation to population density '

import math
import numpy as np
from . import oeqCorrelation as oeq
def get(*xin):

    # OeQ autogenerated correlation for 'NULL'
    TOTAL_LIVING_AREA= oeq.correlation(
    const= 16.9612111141,
    a=     37.3699270344,
    b=     -25.066880729,
    c=     6.04869046956,
    d=     -0.472322343882,
    mode= "log")

    return dict(TOTAL_LIVING_AREA=TOTAL_LIVING_AREA.lookup(*xin))

