# OeQ autogenerated correlation for 'Window/Wall Ratio West in Correlation to the Building Age'

import math
import numpy as np
from . import oeqCorrelation as oeq
def get(*xin):

    # OeQ autogenerated correlation for 'Window to Wall Ratio in Western Direction'
    A_WIN_W_BY_AW= oeq.correlation(
    const= -6820.10365041,
    a=     14.4414621854,
    b=     -0.0114555878046,
    c=     4.03451500345e-06,
    d=     -5.32281636263e-10,
    mode= "lin")

    return dict(A_WIN_W_BY_AW=A_WIN_W_BY_AW.lookup(*xin))

