# -*- coding: utf-8 -*-
"""
/***************************************************************************
 oeqtestbed
                                 A QGIS plugin
 A testing environment for Open e Quarter
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-02-25
        copyright            : (C) 2019 by UdK Berlin
        email                : we.kaul@udk-berlin.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load oeqtestbed class from file oeqtestbed.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .oeq_tb import oeqtestbed
    return oeqtestbed(iface)
